package com.toofreshtowaste.app

import android.app.Application
import android.util.Log
import com.facebook.react.PackageList
import com.facebook.react.ReactApplication
import com.facebook.react.ReactHost
import com.facebook.react.ReactNativeApplicationEntryPoint.loadReactNative
import com.facebook.react.defaults.DefaultReactHost.getDefaultReactHost
import com.margelo.nitro.NitroModulesPackage

class MainApplication : Application(), ReactApplication {

  // React Native 0.87 template: the app exposes a ReactHost only. ReactNativeHost
  // is the legacy-architecture entry point; ReactApplication's default for it
  // now throws. (react-native-restart reaches for it and falls back to
  // Activity.recreate() when it throws - the path it already took in bridgeless.)
  override val reactHost: ReactHost by lazy {
    getDefaultReactHost(
        context = applicationContext,
        packageList =
            PackageList(this).packages.apply {
              add(NitroModulesPackage())
              add(ScreenCapturePackage())
              add(LastKnownLocationPackage())
            },
    )
  }

  override fun onCreate() {
    super.onCreate()
    // Generated by the RN gradle plugin: SoLoader.init(OpenSourceMergedSoMapping),
    // DefaultNewArchitectureEntryPoint.load() and the edge-to-edge feature flag -
    // exactly the three calls this method used to make by hand.
    loadReactNative(this)
    initializeMmkvNative()
  }

  private fun initializeMmkvNative() {
    try {
      val clazz = Class.forName("com.margelo.nitro.mmkv.NitroMmkvOnLoad")
      val companionField = clazz.getDeclaredField("Companion")
      companionField.isAccessible = true
      val companion = companionField.get(null)
      val initMethod = companion.javaClass.getDeclaredMethod("initializeNative")
      initMethod.isAccessible = true
      initMethod.invoke(companion)
      Log.i("MainApplication", "MMKV native library initialized successfully")
    } catch (e: Exception) {
      Log.e("MainApplication", "Failed to initialize MMKV native library", e)
    }
  }
}
