
auth.token=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

defaults.org=tunisniasousse
defaults.project=react-native

defaults.url=https://sentry.io/
