import type { ErrorCode } from './en';

/** Error messages, Arabic. Keys and placeholders mirror `en.ts`. */
export const AR: Readonly<Record<ErrorCode, string>> = {
  BAD_REQUEST: 'تعذّرت معالجة هذا الطلب.',
  UNAUTHORIZED: 'يرجى تسجيل الدخول للمتابعة.',
  FORBIDDEN: 'ليست لديك صلاحية القيام بذلك.',
  NOT_FOUND: 'لم نعثر على ما تبحث عنه.',
  ROUTE_NOT_FOUND: 'هذه الصفحة أو العملية غير موجودة.',
  METHOD_NOT_ALLOWED: 'هذه العملية غير مسموح بها هنا.',
  CONFLICT: 'هذا يتعارض مع الحالة الحالية. حدّث الصفحة وحاول مجددًا.',
  GONE: 'لم يعد هذا متاحًا.',
  PAYLOAD_TOO_LARGE: 'ما أرسلته كبير جدًا.',
  UNPROCESSABLE: 'تعذّرت المعالجة. تحقق من البيانات وحاول مجددًا.',
  TOO_MANY_REQUESTS: 'محاولات كثيرة جدًا. انتظر قليلًا ثم حاول مجددًا.',
  INTERNAL_ERROR: 'حدث خطأ من جهتنا. حاول مرة أخرى.',
  INTERNAL_ERROR_WITH_ID: 'حدث خطأ من جهتنا. إذا تكرر ذلك، تواصل مع الدعم مع رقم الخطأ.',
  SERVICE_UNAVAILABLE: 'هذه الخدمة غير متاحة مؤقتًا. حاول لاحقًا.',
  TIMEOUT: 'استغرق الأمر وقتًا طويلًا. حاول مرة أخرى.',
  ACCESS_DENIED: 'ليس لديك وصول إلى هذا.',
  AUTH_REQUIRED: 'يرجى تسجيل الدخول للمتابعة.',
  ADMIN_REQUIRED: 'لا يمكن القيام بذلك إلا للمسؤولين.',
  MODERATOR_REQUIRED: 'لا يمكن القيام بذلك إلا للمسؤولين والمشرفين.',
  INVALID_ID: 'هذا الرابط أو المعرّف غير صالح.',
  INVALID_DATE: 'أدخل تاريخًا صالحًا.',
  DATE_RANGE_REQUIRED: 'اختر تاريخ البداية وتاريخ النهاية.',
  DATE_RANGE_ORDER: 'يجب أن يسبق تاريخ البداية تاريخ النهاية.',
  DATE_RANGE_TOO_LONG: 'اختر فترة لا تتجاوز {maxDays} يومًا.',
  INVALID_PERIOD: 'اختر إحدى هذه الفترات: {allowed}.',
  INVALID_PAGINATION: 'طلب الصفحة هذا غير صالح.',
  LIMIT_TOO_HIGH: 'طلبت عددًا كبيرًا جدًا من النتائج دفعة واحدة.',
  INVALID_EXPORT_FORMAT: 'اختر JSON أو CSV.',
  INVALID_STATUS: 'اختر إحدى هذه الحالات: {allowed}.',
  INVALID_FILTERS: 'هذه الفلاتر غير صالحة: {details}',
  RATE_LIMITED: 'محاولات كثيرة جدًا. حاول مجددًا بعد {seconds} ثانية.',
  EMAIL_ALREADY_REGISTERED: 'يوجد حساب بهذا البريد الإلكتروني بالفعل.',
  PHONE_ALREADY_REGISTERED: 'رقم الهاتف هذا مرتبط بحساب آخر.',
  USER_ALREADY_EXISTS: 'يوجد حساب بهذه البيانات بالفعل.',
  USER_NOT_FOUND: 'لم نعثر على هذا الحساب.',
  RESOURCE_NOT_FOUND: 'لم نعثر على هذا العنصر.',
  REFUND_ALREADY_REQUESTED: 'تم طلب استرداد لهذا الطلب بالفعل.',
  ZONE_NAME_TAKEN: 'توجد منطقة بهذا الاسم بالفعل.',
  ADMIN_CONTEXT_MISSING: 'جلسة المسؤول غير مكتملة. سجّل الدخول مجددًا.',
  ANNOUNCEMENT_NOT_FOUND: 'هذا الإعلان لم يعد موجودًا.',
  ORDER_CANNOT_BE_CANCELLED: 'لم يعد بالإمكان إلغاء هذا الطلب.',
  ORDER_NOT_REFUNDABLE: 'لا يمكن استرداد هذا الطلب في حالة الدفع الحالية.',
  CONFIG_INVALID: 'هذا الإعداد غير صالح: {details}',
  CONFIG_IMPORT_INVALID: 'الإعداد المستورد غير صالح: {details}',
  CONFIG_IMPORT_NOT_OBJECT: 'الملف المستورد ليس إعدادًا صالحًا.',
  CONFIG_VERSION_NOT_FOUND: 'الإصدار {version} من الإعداد غير موجود.',
  CONFIG_NOT_FOUND: 'لا يوجد إعداد نظام نشط.',
  DAYS_OUT_OF_RANGE: 'اختر بين 1 و365 يومًا.',
  HOURS_OUT_OF_RANGE: 'اختر بين 1 و168 ساعة (7 أيام).',
  DELETED_OFFER_NOT_FOUND: 'هذا العرض المحذوف لم يعد موجودًا.',
  DRIVER_NOT_FOUND: 'لم نعثر على هذا السائق.',
  TRIAL_EXTENSION_REQUIRED: 'حدد تاريخ نهاية جديدًا للتجربة أو عدد أيام التمديد.',
  TRIAL_END_IN_PAST: 'يجب أن يكون تاريخ نهاية التجربة في المستقبل.',
  ESTABLISHMENT_NOT_FOUND: 'لم نعثر على هذا المحل.',
  AUDIT_LOGS_FAILED: 'تعذّر تحميل سجل التدقيق. حاول لاحقًا.',
  ANALYTICS_FAILED: 'تعذّر تحميل هذه الأرقام. حاول لاحقًا.',
  GEOZONE_NOT_FOUND: 'لم نعثر على هذه المنطقة.',
  ORDER_NOT_FOUND: 'لم نعثر على هذا الطلب.',
  CASH_REFUND_NOT_COMPLETED: 'لا يمكن استرداد إلا الطلب النقدي المكتمل. ألغِ الطلب بدلًا من ذلك.',
  TEAM_MEMBER_NOT_FOUND: 'لم نعثر على عضو الفريق هذا.',
  TEAM_ROLE_NOT_EDITABLE: 'لا يمكن تعديل هنا إلا أعضاء الفريق من المسؤولين والمشرفين.',
  TEAM_NOT_MEMBER: 'هذا الشخص ليس عضوًا في الفريق.',
  TEAM_CANNOT_REMOVE_SELF: 'لا يمكنك إزالة نفسك من الفريق.',
  ESTABLISHMENT_NOT_PENDING: 'لا يمكن قبول أو رفض إلا المحلات قيد المراجعة.',
  REASON_REQUIRED: 'اذكر سبب هذا الإجراء.',
  ORDER_ALREADY_REFUNDED: 'تم استرداد هذا الطلب بالفعل.',
  TICKET_NOT_FOUND: 'لم نعثر على تذكرة الدعم هذه.',
  UNKNOWN_BULK_ACTION: 'هذا الإجراء الجماعي غير مدعوم: {action}',
  OFFER_NOT_FOUND: 'هذا العرض لم يعد متاحًا.',
  DASHBOARD_TOO_MANY_WIDGETS: 'تتسع لوحة المعلومات لـ20 أداة كحد أقصى.',
  DASHBOARD_NO_WIDGETS: 'أضف أداة واحدة على الأقل.',
  DASHBOARD_NOT_FOUND: 'لم نعثر على لوحة المعلومات هذه.',
  DASHBOARD_NAME_TAKEN: 'توجد لوحة معلومات بهذا الاسم بالفعل.',
  DASHBOARD_FORBIDDEN: 'ليست لديك صلاحية تعديل لوحة المعلومات هذه.',
  DASHBOARD_TEMPLATE_NOT_FOUND: 'قالب لوحة المعلومات هذا غير متاح لحسابك.',
  DASHBOARD_TEMPLATE_INVALID: 'قالب لوحة المعلومات هذا غير مُعدّ بشكل صحيح.',
  WIDGET_NOT_FOUND: 'لم نعثر على هذه الأداة.',
  WIDGET_POSITION_CONFLICT: 'توجد أداة أخرى في الصف {row}، العمود {column}.',
  WIDGET_POSITION_START: 'تبدأ الأدوات من الصف 1، العمود 1.',
  WIDGET_HEIGHT_RANGE: 'ارتفاع الأداة من 1 إلى 6 صفوف.',
  WIDGET_WIDTH_RANGE: 'عرض الأداة من 1 إلى 12 عمودًا.',
  INVALID_ROLE: 'هذا الدور غير صالح.',
  ACCESS_BLOCKED_SUSPICIOUS: 'تم حظر الوصول مؤقتًا بسبب نشاط مريب.',
  ACCOUNT_ALREADY_VERIFIED: 'هذا الحساب مُفعّل بالفعل.',
  ACCOUNT_INACTIVE: 'هذا الحساب لم يعد نشطًا.',
  CSRF_REQUIRED: 'ينقص جلستك رمز أمان. حدّث الصفحة وحاول مجددًا.',
  CSRF_INVALID: 'فشل التحقق الأمني لجلستك. حدّث الصفحة وحاول مجددًا.',
  GOOGLE_TOKEN_INVALID: 'تعذّر التحقق من تسجيل الدخول عبر Google. حاول مجددًا.',
  GOOGLE_EMAIL_UNVERIFIED: 'البريد الإلكتروني لحساب Google غير مُفعّل.',
  GOOGLE_EMAIL_MISSING: 'حساب Google الخاص بك لا يحتوي على بريد إلكتروني.',
  ACCOUNT_DELETE_FAILED: 'تعذّر حذف حسابك. حاول مرة أخرى.',
  MFA_FAILED: 'تعذّر إكمال التحقق بخطوتين. حاول مرة أخرى.',
  MFA_NOT_ENABLED: 'التحقق بخطوتين غير مُفعّل لهذا الحساب.',
  MFA_NO_BACKUP_CODES: 'لا توجد رموز احتياطية لهذا الحساب.',
  MFA_SETUP_NOT_FOUND: 'لا يوجد إعداد تحقق بخطوتين قيد التنفيذ.',
  MFA_METHOD_NOT_FOUND: 'طريقة التحقق هذه غير مُعدّة.',
  PASSWORD_RESET_FAILED: 'تعذّرت إعادة تعيين كلمة المرور. حاول لاحقًا.',
  RESET_EMAIL_FAILED: 'تعذّر إرسال بريد إعادة التعيين. حاول لاحقًا.',
  SESSION_SETUP_FAILED: 'تعذّر بدء جلستك. حاول مرة أخرى.',
  RESET_TOKEN_INVALID: 'رابط إعادة التعيين هذا غير صالح أو منتهي الصلاحية. اطلب رابطًا جديدًا.',
  SESSION_EXPIRED: 'انتهت جلستك. يرجى تسجيل الدخول مجددًا.',
  LINK_INVALID: 'هذا الرابط غير صالح أو منتهي الصلاحية.',
  VERIFICATION_TOKEN_INVALID: 'رابط التفعيل هذا غير صالح أو منتهي الصلاحية. اطلب رابطًا جديدًا.',
  VERIFICATION_CODE_INVALID: 'رمز التحقق غير صحيح. حاول مرة أخرى.',
  PASSWORD_CHANGE_NOT_REQUIRED: 'هذا الحساب لا يحتاج إلى تغيير كلمة المرور.',
  PASSWORD_POLICY:
    'يجب أن تتكون كلمة المرور من 12 حرفًا على الأقل مع حرف كبير وحرف صغير ورقم وأحد الرموز @$!%*?&.',
  PASSWORD_TOO_WEAK:
    'كلمة المرور هذه سهلة التخمين. جرّب عبارة أطول أو مزيجًا أقل شيوعًا من الكلمات والرموز.',
  EMAIL_NOT_VERIFIED: 'يرجى تفعيل بريدك الإلكتروني قبل تسجيل الدخول.',
  REFRESH_TOKEN_MISSING: 'انتهت جلستك. يرجى تسجيل الدخول مجددًا.',
  SESSION_NOT_FOUND: 'هذه الجلسة لم تعد موجودة.',
  TENANT_CONTEXT_MISSING: 'حسابك غير مرتبط بنشاط تجاري بعد.',
  EMAIL_REQUIRED: 'أدخل بريدك الإلكتروني.',
  VERIFICATION_SESSION_EXPIRED: 'انتهت جلسة التحقق. يرجى تسجيل الدخول مجددًا.',
  SIGN_IN_FAILED: 'تعذّر تسجيل دخولك. حاول مرة أخرى.',
  FILE_DELETE_FAILED: 'تعذّر حذف الملف. حاول مرة أخرى.',
  FILE_TYPE_UNKNOWN: 'لم نتعرّف على نوع هذا الملف.',
  FILE_URL_FAILED: 'تعذّر فتح الملف. حاول مرة أخرى.',
  FILE_EMPTY: 'هذا الملف فارغ.',
  FILE_TYPE_MISMATCH: 'محتوى هذا الملف لا يطابق نوعه.',
  FILE_NOT_FOUND: 'لم نعثر على هذا الملف.',
  FILE_TOO_LARGE: 'هذا الملف أكبر من {maxMb} ميغابايت.',
  FILE_TYPE_NOT_ALLOWED: 'هذا النوع من الملفات غير مسموح به.',
  FILE_UPLOAD_FAILED: 'تعذّر رفع الملف. حاول مرة أخرى.',
  IMAGE_PROCESSING_FAILED: 'تعذّرت معالجة هذه الصورة. جرّب صورة أخرى.',
  FILE_REQUIRED: 'اختر ملفًا لرفعه.',
  STORAGE_UNAVAILABLE: 'تخزين الملفات غير متاح مؤقتًا. حاول لاحقًا.',
  PRO_PLAN_REQUIRED: 'هذه الميزة تتطلب اشتراك Pro.',
  APP_UPDATE_REQUIRED: 'يرجى تحديث التطبيق للمتابعة.',
  DONATION_FAILED: 'تعذّر تسجيل التبرع. حاول مرة أخرى.',
  DONATION_STATS_FAILED: 'تعذّر تحميل أرقام التبرعات. حاول لاحقًا.',
  ORDER_TOTAL_INVALID: 'يجب أن يكون مجموع الطلب أكبر من صفر.',
  DRIVER_CASH_CHANGED: 'تغيّرت سجلات النقد أثناء الحفظ. حاول مرة أخرى.',
  DRIVER_PROFILE_NOT_FOUND: 'ملف السائق الخاص بك غير مُعدّ. تواصل مع فريق TFTW.',
  AMOUNT_ABOVE_ZERO: 'أدخل مبلغًا أكبر من صفر.',
  AMOUNT_REQUIRED: 'أدخل المبلغ المُسلَّم.',
  DRIVER_BUSY: 'أنهِ توصيلك الحالي قبل قبول طلب آخر.',
  DRIVER_NO_PENDING_RECOVERY: 'لا يوجد توصيل فاشل بانتظار قرار.',
  DRIVER_ORDER_TAKEN: 'تم أخذ هذا الطلب من سائق آخر بالفعل.',
  DRIVER_ORDER_NOT_YOURS: 'هذا الطلب غير مُسند إليك أو تغيّرت حالته.',
  DRIVER_CASH_MISMATCH: 'المبلغ المحصّل لا يطابق هذا الطلب. تحقق منه وحاول مجددًا.',
  DRIVER_FLOAT_INSUFFICIENT: 'لا يملك السائق سوى {amount} دينار من الرصيد النقدي.',
  DRIVER_UNKNOWN: 'لم نعثر على هذا السائق.',
  DRIVER_MERCHANT_FAULT_RETURN: 'إذا كان التاجر مخطئًا، أعد الطعام إليه واسترجع المبلغ.',
  DRIVER_ALREADY_COLLECTED:
    'لقد استلمت هذا الطلب ودفعت ثمنه بالفعل. أبلغ عن مشكلة بدلًا من ذلك حتى يُحتسب الطعام والمال.',
  DRIVER_OFFLINE: 'فعّل وضع الاتصال لقبول الطلبات.',
  DOCUMENT_ID_REQUIRED: 'حدد المستند الإضافي المقصود.',
  DOCUMENT_TYPE_INVALID: 'نوع المستند هذا غير صالح.',
  DOCUMENT_REQUIRED: 'اختر مستندًا لرفعه.',
  DOCUMENTS_NOT_FOUND: 'لم تُرفع أي مستندات لهذا المحل.',
  DOCUMENT_PDF_ONLY: 'يجب أن تكون المستندات القانونية بصيغة PDF.',
  LOCATION_ALREADY_REGISTERED: 'موقع هذا النشاط مسجّل بالفعل. إذا كان لك، تواصل مع الدعم.',
  ESTABLISHMENT_LIMIT_REACHED: 'لديك محل بالفعل. أنشئ مؤسسة لإضافة مواقع أخرى.',
  INVALID_NUMBER: 'أدخل رقمًا صالحًا.',
  ESTABLISHMENT_NOT_YOURS: 'لا يمكنك إدارة إلا محلك الخاص.',
  FAVORITE_LIST_NAME_TAKEN: 'لديك قائمة بهذا الاسم بالفعل.',
  FAVORITE_LIST_NOT_FOUND: 'لم نعثر على هذه القائمة.',
  FAVORITE_NOT_FOUND: 'هذه المفضلة لم تعد موجودة.',
  FAVORITE_ALREADY_ADDED: 'هذا موجود في مفضلتك بالفعل.',
  FAVORITE_ALREADY_IN_LIST: 'هذا موجود في القائمة بالفعل.',
  INVALID_COORDINATES: 'هذا الموقع غير صالح.',
  ESTABLISHMENT_LOCATION_MISSING: 'هذا المحل ليس له موقع بعد.',
  GEOCODING_FAILED: 'تعذّر البحث عن هذا العنوان. حاول مرة أخرى.',
  GEOCODING_UNAVAILABLE: 'البحث عن العناوين غير متاح مؤقتًا. حاول لاحقًا.',
  SAVED_LOCATION_NOT_FOUND: 'لم نعثر على هذا المكان المحفوظ.',
  LOCATION_PREFERENCES_NOT_FOUND: 'تعذّر العثور على إعدادات موقعك.',
  STOCK_INSUFFICIENT: 'لا يوجد مخزون كافٍ.',
  STOCK_RESERVATION_INVALID: 'المخزون المحجوز لا يطابق هذا التغيير.',
  INVENTORY_ITEM_NOT_FOUND: 'لم نعثر على هذا العنصر في مخزونك.',
  LOYALTY_INSUFFICIENT_POINTS: 'ليست لديك نقاط كافية. رصيدك المتاح {available} نقطة.',
  LOYALTY_NOT_ENOUGH_POINTS: 'ليست لديك نقاط كافية لذلك.',
  LOYALTY_ACCOUNT_EXISTS: 'لهذا الحساب حساب ولاء بالفعل.',
  LOYALTY_ACCOUNT_NOT_FOUND: 'حساب الولاء الخاص بك غير مُنشأ بعد.',
  CHALLENGE_NOT_ENDED: 'لم ينتهِ أي تحدٍّ بعد، لذا لا توجد جائزة للمطالبة بها.',
  LOYALTY_TIERS_MISSING: 'مستويات الولاء غير مُعدّة.',
  REFERRER_NOT_FOUND: 'رابط الإحالة هذا غير صالح.',
  LEADERBOARD_NOT_LISTED: 'أنت غير موجود في الترتيب.',
  LEADERBOARD_CLAIM_GRAND_PRIZE: 'أنت في المراتب الأولى: اطلب الجائزة الكبرى بدلًا من الخصم.',
  MODERATION_CONFLICT: 'تعذّر التطبيق: لدى الحساب إجراء متعارض بالفعل.',
  MODERATION_ACTION_NOT_FOUND: 'لم نعثر على إجراء الإشراف هذا.',
  MODERATION_RATE_LIMITED: 'إجراءات إشراف كثيرة جدًا. حاول مجددًا بعد {seconds} ثانية.',
  MODERATION_ACTION_NOT_ACTIVE: 'لا يمكن إلغاء إلا الإجراءات النشطة.',
  REPORT_RATE_LIMITED: 'أرسلت بلاغات كثيرة جدًا. حاول مجددًا بعد {seconds} ثانية.',
  REPORT_NOT_FOUND: 'لم نعثر على هذا البلاغ.',
  REPORT_NOT_ASSIGNED: 'هذا البلاغ مُسند إلى شخص آخر.',
  MODERATION_NOT_OWNER: 'لا يمكنك تعديل إلا الإجراءات التي أنشأتها.',
  REPORT_DUPLICATE: 'لقد أبلغت عن هذا خلال آخر 24 ساعة بالفعل.',
  BULK_TOO_LARGE: 'أرسل إلى {max} مستلمًا أو أقل في كل مرة.',
  SMS_OPT_OUT_FAILED: 'تعذّر تحديث تفضيلات الرسائل القصيرة. حاول مرة أخرى.',
  INVALID_PHONE: 'أدخل رقم هاتف صالحًا، مثل ‎+21612345678‎.',
  WEBHOOK_INVALID: 'طلب الويب هوك هذا غير صالح.',
  SMS_OPT_OUT_NOT_FOUND: 'لا يوجد إلغاء اشتراك في الرسائل لهذا الرقم.',
  SMS_PAYLOAD_INVALID: 'تحتاج الرسالة القصيرة إلى عنوان ونص.',
  OFFER_SLOT_REQUIRED: 'أضف فترة استلام واحدة على الأقل.',
  OFFER_START_IN_PAST: 'لا يمكن أن يكون تاريخ البداية في الماضي.',
  OFFER_END_BEFORE_START: 'يجب أن يكون تاريخ النهاية بعد تاريخ البداية.',
  OFFER_HAS_RESERVATIONS: 'لهذا العرض حجوزات نشطة. انتظر اكتمالها أو ألغها أولًا.',
  OFFER_DISCOUNT_OUT_OF_RANGE: 'يجب أن يكون الخصم بين 40% و90%. أسعارك تعطي {discount}%.',
  OFFER_PRICE_ORDER: 'يجب أن يكون السعر المخفّض أقل من السعر الأصلي.',
  OFFER_SLOT_CAPACITY: 'اسمح بطلب واحد على الأقل لكل فترة.',
  IMAGES_REQUIRED: 'أضف صورة واحدة على الأقل.',
  OFFER_QUANTITY_UNAVAILABLE: 'لا يتبقى عدد كافٍ من السلال.',
  OFFER_STATE_UNCHANGED: 'هذا العرض في هذه الحالة بالفعل.',
  OFFER_PRICES_REQUIRED: 'أدخل السعر الأصلي والسعر المخفّض.',
  OFFER_SLOT_ORDER: 'يجب أن تبدأ فترة الاستلام قبل نهايتها.',
  QUANTITY_ABOVE_ZERO: 'يجب أن تكون الكمية أكبر من صفر.',
  OFFER_EXPIRED: 'انتهت صلاحية هذا العرض.',
  OFFER_NOT_ACTIVE: 'هذا العرض غير متاح حاليًا.',
  OFFER_NOT_YOURS: 'لا يمكنك إدارة إلا عروض محلك.',
  ORDER_NEEDS_OFFER: 'أضف عرضًا واحدًا على الأقل إلى طلبك.',
  PICKUP_EXTENSION_NOT_ALLOWED: 'لا يمكن تمديد وقت الاستلام لهذا الطلب.',
  ORDER_INVALID_TRANSITION: 'لا يمكن نقل هذا الطلب من {from} إلى {to}.',
  CASH_PICKUP_ONLY:
    'الدفع نقدًا عند الشباك متاح للاستلام فقط. للتوصيل، ادفع للسائق أو عبر الإنترنت.',
  PAY_ON_DELIVERY_ONLY:
    'الدفع عند التوصيل متاح لطلبات التوصيل فقط. للاستلام، ادفع عند الشباك أو عبر الإنترنت.',
  CUSTOMER_NOT_FOUND: 'لم نعثر على هذا العميل.',
  ORDER_CREATE_FAILED: 'تعذّر إرسال طلبك. حاول مرة أخرى.',
  INVALID_GRANULARITY: 'اختر أحد الخيارات: {allowed}.',
  INVALID_GRANULARITY_VALUE: 'اختر قيمة بين 1 و{max}.',
  PICKUP_CODE_INVALID: 'رمز الاستلام هذا غير صالح.',
  PICKUP_QR_REQUIRED: 'امسح رمز QR الخاص بالعميل لتأكيد الاستلام.',
  PICKUP_EXTENSION_NOT_FOUND: 'لا يوجد طلب تمديد لهذا الطلب.',
  ORDER_OFFERS_UNAVAILABLE: 'بعض عناصر طلبك لم تعد متاحة.',
  PICKUP_MERCHANT_ONLY: 'لا يمكن تأكيد هذا الاستلام إلا من المحل.',
  PICKUP_OWNER_ONLY: 'لا يمكن تأكيد الاستلام إلا من العميل صاحب الطلب.',
  ORDER_NOT_CANCELLABLE: 'لم يعد بالإمكان إلغاء هذا الطلب.',
  ORDER_ALREADY_CANCELLED: 'تم إلغاء هذا الطلب بالفعل.',
  ORDER_NOT_LOCKED: 'هذا الطلب غير مقفل.',
  ORDER_STATUS_NOT_SETTABLE: 'لا يمكن تعيين الحالة {status} مباشرة. استخدم إجراء الطلب المناسب.',
  ORDER_NOT_YOURS: 'لا يمكنك إدارة هذا الطلب.',
  INVITATION_ALREADY_PENDING: 'لهذا البريد دعوة معلّقة بالفعل.',
  ORGANIZATION_LAST_ESTABLISHMENT:
    'تحتاج المؤسسة إلى محل واحد على الأقل. احذف المؤسسة بدلًا من ذلك.',
  ORGANIZATION_ESTABLISHMENT_NOT_FOUND: 'هذا المحل ليس جزءًا من المؤسسة.',
  ESTABLISHMENT_REQUIRED: 'اختر محلًا.',
  INVITATION_EXPIRED: 'انتهت صلاحية هذه الدعوة.',
  INVITATION_NOT_VALID: 'هذه الدعوة لم تعد صالحة.',
  INVITATION_NOT_FOUND: 'لم نعثر على هذه الدعوة.',
  INVITATION_NOT_PENDING: 'لا يمكن إلغاء إلا الدعوات المعلّقة.',
  ORGANIZATION_OWNER_ONLY: 'لا يمكن القيام بذلك إلا لمالك المؤسسة.',
  ORGANIZATION_NOT_FOUND: 'لم نعثر على هذه المؤسسة.',
  ORGANIZATION_ESTABLISHMENT_MISMATCH: 'هذا المحل لا ينتمي إلى المؤسسة.',
  ORGANIZATION_ESTABLISHMENT_EXISTS: 'هذا المحل جزء من المؤسسة بالفعل.',
  ORGANIZATION_LIMIT_REACHED: 'لديك مؤسسة بالفعل. يمكن لكل تاجر امتلاك مؤسسة واحدة.',
  ORGANIZATION_NOT_YOURS: 'لا يمكنك عرض إلا مؤسستك.',
  PAYOUT_ALREADY_RUNNING: 'هناك عملية دفع قيد التنفيذ. انتظر انتهاءها قبل بدء أخرى.',
  ORDER_NOT_AWAITING_PAYMENT: 'هذا الطلب لا ينتظر دفعًا.',
  PAYMENT_NOT_FOUND: 'لم نعثر على هذا الدفع.',
  PAYMENT_ALREADY_SUCCEEDED: 'تمت عملية الدفع السابقة بنجاح. تم تحديث طلبك.',
  PAYMENT_VERIFY_FAILED: 'تعذّر التحقق من حالة الدفع. حاول مرة أخرى.',
  MERCHANT_NOT_FOUND: 'لم نعثر على هذا التاجر.',
  PAYMENT_AMOUNT_INVALID: 'مبلغ الدفع غير صالح.',
  PAYMENT_FAILED: 'تعذّر بدء عملية الدفع. حاول مرة أخرى.',
  PAYMENT_UNAVAILABLE: 'الدفع عبر الإنترنت غير متاح مؤقتًا. حاول لاحقًا.',
  SUBSCRIPTION_NOT_YOURS: 'لا يمكنك إدارة إلا اشتراك محلك.',
  SUBSCRIPTION_RENEW_TOO_EARLY:
    'اشتراكك نشط لمدة {days} يومًا أخرى. يمكنك التجديد عندما يتبقى أقل من 7 أيام.',
  COMMUNITY_FUND_NO_ESTABLISHMENT:
    'لم نعثر على المحل المرتبط بحسابك، لذا لا يوجد صندوق مجتمعي لعرضه بعد.',
  REVIEW_NOT_YOURS: 'لا يمكنك تعديل إلا تقييماتك.',
  REVIEW_RESPONSE_NOT_ALLOWED: 'لا يمكنك الرد إلا على تقييمات محلك.',
  REVIEW_ORDER_NOT_COMPLETED: 'يمكنك تقييم الطلب بعد استلامه.',
  REVIEW_ORDER_NOT_YOURS: 'لا يمكنك تقييم إلا طلباتك.',
  REVIEW_TOO_OLD: 'لا يمكن تعديل التقييمات إلا خلال 30 يومًا.',
  REVIEW_ESTABLISHMENT_INACTIVE: 'هذا المحل غير نشط، لذا لا يمكن تقييمه.',
  REVIEW_OWN_ESTABLISHMENT: 'لا يمكنك تقييم محلك.',
  REVIEW_FAILED: 'تعذّر حفظ التقييم. حاول مرة أخرى.',
  REVIEWS_LOAD_FAILED: 'تعذّر تحميل التقييمات. حاول مرة أخرى.',
  REVIEW_OFFER_MISMATCH: 'هذا العرض لا ينتمي إلى المحل الذي تقيّمه.',
  REVIEW_NOT_FOUND: 'لم نعثر على هذا التقييم.',
  REVIEWER_INACTIVE: 'لا يمكن لهذا الحساب نشر تقييمات.',
  REVIEW_ALREADY_REPORTED: 'لقد أبلغت عن هذا التقييم بالفعل.',
  REVIEW_ALREADY_RESPONDED: 'لقد رددت على هذا التقييم بالفعل.',
  REVIEW_ALREADY_EXISTS: 'لقد قيّمت هذا الطلب بالفعل.',
  PASSWORD_OAUTH_ACCOUNT: 'هذا الحساب يسجّل الدخول عبر Google، لذا لا توجد كلمة مرور لتعيينها.',
  CURRENT_PASSWORD_INCORRECT: 'كلمة المرور الحالية غير صحيحة.',
  FIRST_NAME_REQUIRED: 'أدخل اسمك.',
  LAST_NAME_REQUIRED: 'أدخل لقبك.',
  PASSWORD_REQUIRED: 'أدخل كلمة المرور.',
  VERIFICATION_SEND_FAILED: 'تعذّر إرسال رمز التحقق. حاول مرة أخرى.',
  INVALID_SETTING: 'هذا الإعداد غير صالح.',
  MAX_DISTANCE_RANGE: 'اختر مسافة بين 100 م و50 كم.',
  VERIFICATION_ATTEMPTS_EXCEEDED: 'محاولات كثيرة جدًا. اطلب رمزًا جديدًا.',
  MIN_DISCOUNT_RANGE: 'اختر حدًا أدنى للخصم بين 0% و100%.',
  CONSENT_NOT_FOUND: 'لا توجد موافقة نشطة من هذا النوع.',
  VERIFICATION_CODE_MISSING: 'اطلب رمز تحقق أولًا.',
  PHONE_MISMATCH: 'رقم الهاتف هذا لا يطابق الرقم قيد التحقق.',
  PHONE_VERIFICATION_UNAVAILABLE: 'التحقق من الهاتف غير متاح مؤقتًا. حاول لاحقًا.',
  ACCOUNT_CREATE_FAILED: 'تعذّر إنشاء حسابك. حاول مرة أخرى.',
  USER_NOT_DELETED: 'هذا الحساب غير محذوف.',
  VERIFICATION_CODE_EXPIRED: 'انتهت صلاحية هذا الرمز. اطلب رمزًا جديدًا.',
  BALLOT_NOT_OPEN: 'التصويت غير مفتوح حاليًا.',
  BALLOT_CLOSED: 'انتهى التصويت.',
  NOT_ELIGIBLE: 'لست مؤهلًا للتصويت في هذه الجولة.',
  ALREADY_VOTED: 'لقد صوّتت في هذه الجولة بالفعل.',
  INVALID_PRIZE: 'هذه الجائزة ليست ضمن التصويت.',
  SNAPSHOT_NOT_READY: 'يجري تحضير التصويت. حاول مجددًا بعد بضع دقائق.',
  NO_ACTIVE_CYCLE: 'لا يوجد تصويت مجتمعي حاليًا.',
  FIELD_LOCKED_AFTER_ACTIVATION: 'لا يمكن تغيير هذا بعد الآن: بدأ التصويت.',
  VOTE_FIRST_TO_SEE_RESULTS: 'صوّت أولًا لرؤية النتائج.',
  VOTING_CYCLE_EXISTS: 'يوجد تصويت آخر قيد التنفيذ.',
  VOTING_CYCLE_CHANGED: 'تغيّر هذا التصويت أثناء تعديلك. حدّث الصفحة وحاول مجددًا.',
  VOTING_CYCLE_INVALID_STATE: 'هذا الإجراء غير متاح والتصويت في حالة {status}.',
  VOTING_CLAIM_FINAL: 'طلب الجائزة هذا مغلق ولا يمكن تغييره.',
  VOTING_CYCLE_NOT_DRAFT: 'لا يمكن تعديل إلا التصويت المسوّدة بهذه الطريقة.',
  VOTING_NO_COMPLETED_CYCLE: 'لا يوجد تصويت مكتمل بجائزة للمطالبة بها بعد.',
  VOTING_PRIZE_TOP_ONLY: 'لا يمكن المطالبة بهذه الجائزة إلا لأول {count} في الترتيب.',
  VOTING_CLAIM_NOT_FOUND: 'لم نعثر على طلب الجائزة هذا.',
  VOTING_SNAPSHOT_RETRY_INVALID:
    'لا يمكن إعادة بناء قائمة المصوّتين إلا والتصويت مفتوح وغير جاهز بعد.',
  VOTING_CYCLE_NOT_FOUND: 'لم نعثر على هذا التصويت.',
  VOTING_PRIZE_ALREADY_CLAIMED: 'لقد طالبت بجائزتك لهذا التصويت بالفعل.',
  VALIDATION_FAILED: 'بعض البيانات غير صالحة. تحقق منها وحاول مجددًا.',
  VALIDATION_REQUIRED: 'هذا الحقل مطلوب.',
  VALIDATION_EMAIL: 'أدخل بريدًا إلكترونيًا صالحًا.',
  VALIDATION_MIN_LENGTH: 'أدخل {min} أحرف على الأقل.',
  VALIDATION_MAX_LENGTH: 'أدخل {max} حرفًا كحد أقصى.',
  VALIDATION_LENGTH: 'أدخل بين {min} و{max} حرفًا.',
  VALIDATION_MIN: 'أدخل قيمة لا تقل عن {min}.',
  VALIDATION_MAX: 'أدخل قيمة لا تزيد عن {max}.',
  VALIDATION_NUMBER: 'أدخل رقمًا.',
  VALIDATION_INTEGER: 'أدخل عددًا صحيحًا.',
  VALIDATION_POSITIVE: 'أدخل رقمًا أكبر من صفر.',
  VALIDATION_BOOLEAN: 'اختر نعم أو لا.',
  VALIDATION_DATE: 'أدخل تاريخًا صالحًا.',
  VALIDATION_ENUM: 'اختر أحد الخيارات المتاحة.',
  VALIDATION_FORMAT: 'هذا ليس بالصيغة المتوقعة.',
  VALIDATION_PHONE: 'أدخل رقم هاتف صالحًا، مثل ‎+21612345678‎.',
  VALIDATION_URL: 'أدخل رابطًا صالحًا.',
  VALIDATION_ID: 'هذا المعرّف غير صالح.',
  VALIDATION_TEXT: 'أدخل نصًا.',
  VALIDATION_LIST: 'يجب أن يكون هذا قائمة.',
  VALIDATION_LIST_MIN: 'أضف {min} عناصر على الأقل.',
  VALIDATION_LIST_MAX: 'أضف {max} عناصر كحد أقصى.',
  VALIDATION_COORDINATE: 'هذا الموقع غير صالح.',
  VALIDATION_NOT_ALLOWED: 'هذا الحقل غير مسموح به.',
  VALIDATION_INVALID: 'هذه القيمة غير صالحة.',
  ACCOUNT_LOCKED: 'محاولات فاشلة كثيرة جدًا. حسابك مقفل حاليًا؛ حاول لاحقًا.',
  INVALID_CREDENTIALS: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
  LOGIN_TEMPORARILY_BLOCKED: 'محاولات تسجيل دخول كثيرة جدًا. انتظر ثم حاول لاحقًا.',
  ACCOUNT_SUSPENDED: 'هذا الحساب موقوف. تواصل مع الدعم للمساعدة.',
  PASSWORD_REUSED: 'اختر كلمة مرور لم تستخدمها في آخر {count} كلمات مرور.',
  EMAIL_VERIFICATION_FAILED: 'تعذّر تفعيل بريدك الإلكتروني. حاول مرة أخرى.',
  VERIFICATION_RESEND_FAILED: 'تعذّر إرسال بريد التفعيل. حاول مرة أخرى.',
  QUERY_TOO_COMPLEX: 'هذا البحث معقد جدًا. بسّط الفلاتر وحاول مجددًا.',
  TRIAL_EXPIRED: 'انتهى اشتراكك. جدّده للمتابعة.',
  OFFER_SLOT_CAPACITY_EXCEEDED:
    'تسمح فترات الاستلام بـ{capacity} طلبًا بينما المتاح {quantity} سلة فقط. قلّل الطلبات لكل فترة أو أضف سلالًا.',
  OFFER_CANNOT_REACTIVATE: 'لا يمكن إعادة تفعيل إلا العروض المنتهية أو الملغاة أو النافدة.',
  OFFER_CANNOT_TOGGLE: 'لا يمكن تشغيل أو إيقاف إلا العروض النشطة أو المسوّدة.',
  ESTABLISHMENT_PENDING_APPROVAL: 'محلك قيد المراجعة. يمكنك نشر العروض بعد قبوله من فريقنا.',
  ESTABLISHMENT_SUSPENDED: 'محلك موقوف، لذا لا يمكن نشر العروض. تواصل مع الدعم.',
  ESTABLISHMENT_REJECTED: 'لم يتم قبول محلك، لذا لا يمكن نشر العروض. تواصل مع الدعم لمعرفة السبب.',
  ESTABLISHMENT_INACTIVE: 'محلك غير نشط. أعد تفعيله قبل نشر العروض.',
  PHONE_VERIFICATION_REQUIRED: 'أضف رقم هاتفك لإتمام الطلب.',
  INSUFFICIENT_STOCK: 'بعض عناصر طلبك لم تعد متاحة.',
  PICKUP_LOCKED: 'تم قفل الاستلام بعد رموز خاطئة كثيرة. تواصل مع الدعم.',
  ORDER_NOT_READY: 'هذا الطلب غير جاهز للاستلام بعد. انتظر تأكيد التاجر.',
  CODE_EXPIRED: 'انتهت صلاحية رمز الاستلام: انتهت فترة الاستلام.',
  PICKUP_ALREADY_DONE: 'تم تأكيد هذا الاستلام بالفعل.',
  CANCELLATION_WINDOW_CLOSED: 'لا يمكن إلغاء الطلبات في الساعة التي تسبق الاستلام.',
  PAYMENT_METHOD_UNSUPPORTED: 'طريقة الدفع هذه غير متاحة. ادفع نقدًا أو عبر الإنترنت.',
  ESTABLISHMENT_CREATE_FAILED: 'تعذّر إنشاء المحل. حاول مرة أخرى.',
  USER_LOAD_FAILED: 'تعذّر تحميل هذا الحساب. حاول مرة أخرى.',
  PROFILE_UPDATE_FAILED: 'تعذّر تحديث الملف الشخصي. حاول مرة أخرى.',
  LOCATION_UPDATE_FAILED: 'تعذّر تحديث الموقع. حاول مرة أخرى.',
  USER_STATUS_UPDATE_FAILED: 'تعذّر تغيير حالة الحساب. حاول مرة أخرى.',
  PHONE_VERIFICATION_FAILED: 'تعذّر التحقق من رقم هاتفك. حاول مرة أخرى.',
  LOCATION_PREFERENCES_FAILED: 'تعذّر تحميل إعدادات موقعك أو حفظها. حاول مرة أخرى.',
  PRIVACY_REQUEST_FAILED: 'تعذّر حفظ اختيار الخصوصية. حاول مرة أخرى.',
  PRIVACY_EXPORT_FAILED: 'تعذّر تصدير بياناتك. حاول مرة أخرى.',
  PRIVACY_DELETION_FAILED: 'تعذّرت معالجة طلب الحذف. حاول مرة أخرى.',
  CHALLENGE_PRIZE_ALREADY_CLAIMED: 'لقد طالبت بجائزتك لهذا التحدي بالفعل.',
};
