/**
 * Error messages, English. The keys of this object ARE the error codes: every
 * code a client can receive is listed here, and `fr` and `ar` are typed
 * `Record<ErrorCode, string>`, so a code without a translation does not compile.
 *
 * Copy rules: written for the person using the app. No internal ids, no field
 * names, no developer instructions. Placeholders are `{name}`, filled from
 * `appError(code, params)`; every locale must use the same placeholders
 * (checked by error-catalog.spec.ts).
 *
 * A code is a contract with the clients that branch on it. Rename one and grep
 * apps/web and apps/mobile first.
 */
export const EN = {
  BAD_REQUEST: 'This request could not be processed.',
  UNAUTHORIZED: 'Please sign in to continue.',
  FORBIDDEN: 'You do not have permission to do this.',
  NOT_FOUND: 'We could not find what you are looking for.',
  ROUTE_NOT_FOUND: 'This page or action does not exist.',
  METHOD_NOT_ALLOWED: 'This action is not allowed here.',
  CONFLICT: 'This conflicts with the current state. Refresh and try again.',
  GONE: 'This is no longer available.',
  PAYLOAD_TOO_LARGE: 'What you sent is too large.',
  UNPROCESSABLE: 'This could not be processed. Check the details and try again.',
  TOO_MANY_REQUESTS: 'Too many attempts. Please wait a moment and try again.',
  INTERNAL_ERROR: 'Something went wrong on our side. Please try again.',
  INTERNAL_ERROR_WITH_ID:
    'Something went wrong on our side. If it keeps happening, contact support with the error ID.',
  SERVICE_UNAVAILABLE: 'This service is temporarily unavailable. Please try again later.',
  TIMEOUT: 'This took too long. Please try again.',
  ACCESS_DENIED: 'You do not have access to this.',
  AUTH_REQUIRED: 'Please sign in to continue.',
  ADMIN_REQUIRED: 'Only administrators can do this.',
  MODERATOR_REQUIRED: 'Only administrators and moderators can do this.',
  INVALID_ID: 'This link or identifier is not valid.',
  INVALID_DATE: 'Enter a valid date.',
  DATE_RANGE_REQUIRED: 'Choose both a start and an end date.',
  DATE_RANGE_ORDER: 'The start date must be before the end date.',
  DATE_RANGE_TOO_LONG: 'Choose a period of {maxDays} days or less.',
  INVALID_PERIOD: 'Choose one of these periods: {allowed}.',
  INVALID_PAGINATION: 'This page request is not valid.',
  LIMIT_TOO_HIGH: 'You asked for too many results at once.',
  INVALID_EXPORT_FORMAT: 'Choose JSON or CSV.',
  INVALID_STATUS: 'Choose one of these statuses: {allowed}.',
  INVALID_FILTERS: 'These filters are not valid: {details}',
  RATE_LIMITED: 'Too many attempts. Try again in {seconds} seconds.',
  EMAIL_ALREADY_REGISTERED: 'An account with this email already exists.',
  PHONE_ALREADY_REGISTERED: 'This phone number is already linked to another account.',
  USER_ALREADY_EXISTS: 'An account with these details already exists.',
  USER_NOT_FOUND: 'We could not find this account.',
  RESOURCE_NOT_FOUND: 'We could not find this item.',
  REFUND_ALREADY_REQUESTED: 'A refund has already been requested for this order.',
  ZONE_NAME_TAKEN: 'A zone with this name already exists.',
  ADMIN_CONTEXT_MISSING: 'Your admin session is incomplete. Sign in again.',
  ANNOUNCEMENT_NOT_FOUND: 'This announcement no longer exists.',
  ORDER_CANNOT_BE_CANCELLED: 'This order can no longer be cancelled.',
  ORDER_NOT_REFUNDABLE: 'This order cannot be refunded in its current payment state.',
  CONFIG_INVALID: 'This configuration is not valid: {details}',
  CONFIG_IMPORT_INVALID: 'The imported configuration is not valid: {details}',
  CONFIG_IMPORT_NOT_OBJECT: 'The imported file is not a valid configuration.',
  CONFIG_VERSION_NOT_FOUND: 'Configuration version {version} does not exist.',
  CONFIG_NOT_FOUND: 'There is no active system configuration.',
  DAYS_OUT_OF_RANGE: 'Choose between 1 and 365 days.',
  HOURS_OUT_OF_RANGE: 'Choose between 1 and 168 hours (7 days).',
  DELETED_OFFER_NOT_FOUND: 'This deleted offer no longer exists.',
  DRIVER_NOT_FOUND: 'We could not find this driver.',
  TRIAL_EXTENSION_REQUIRED: 'Set a new trial end date or a number of days to extend it by.',
  TRIAL_END_IN_PAST: 'The trial end date must be in the future.',
  ESTABLISHMENT_NOT_FOUND: 'We could not find this establishment.',
  AUDIT_LOGS_FAILED: 'Could not load the audit logs. Please try again later.',
  ANALYTICS_FAILED: 'Could not load these figures. Please try again later.',
  GEOZONE_NOT_FOUND: 'We could not find this zone.',
  ORDER_NOT_FOUND: 'We could not find this order.',
  CASH_REFUND_NOT_COMPLETED:
    'Only a completed cash order can be refunded. Cancel the order instead.',
  TEAM_MEMBER_NOT_FOUND: 'We could not find this team member.',
  TEAM_ROLE_NOT_EDITABLE: 'Only admin and moderator team members can be changed here.',
  TEAM_NOT_MEMBER: 'This person is not a team member.',
  TEAM_CANNOT_REMOVE_SELF: 'You cannot remove yourself from the team.',
  ESTABLISHMENT_NOT_PENDING: 'Only establishments waiting for review can be approved or rejected.',
  REASON_REQUIRED: 'Give a reason for this action.',
  ORDER_ALREADY_REFUNDED: 'This order was already refunded.',
  TICKET_NOT_FOUND: 'We could not find this support ticket.',
  UNKNOWN_BULK_ACTION: 'This bulk action is not supported: {action}',
  OFFER_NOT_FOUND: 'This offer is no longer available.',
  DASHBOARD_TOO_MANY_WIDGETS: 'A dashboard can hold up to 20 widgets.',
  DASHBOARD_NO_WIDGETS: 'Add at least one widget.',
  DASHBOARD_NOT_FOUND: 'We could not find this dashboard.',
  DASHBOARD_NAME_TAKEN: 'A dashboard with this name already exists.',
  DASHBOARD_FORBIDDEN: 'You do not have permission to change this dashboard.',
  DASHBOARD_TEMPLATE_NOT_FOUND: 'This dashboard template is not available for your account.',
  DASHBOARD_TEMPLATE_INVALID: 'This dashboard template is not set up correctly.',
  WIDGET_NOT_FOUND: 'We could not find this widget.',
  WIDGET_POSITION_CONFLICT: 'Another widget already sits at row {row}, column {column}.',
  WIDGET_POSITION_START: 'Widgets start at row 1, column 1.',
  WIDGET_HEIGHT_RANGE: 'A widget is 1 to 6 rows high.',
  WIDGET_WIDTH_RANGE: 'A widget is 1 to 12 columns wide.',
  INVALID_ROLE: 'This role is not valid.',
  ACCESS_BLOCKED_SUSPICIOUS: 'Access is temporarily blocked because of suspicious activity.',
  ACCOUNT_ALREADY_VERIFIED: 'This account is already verified.',
  ACCOUNT_INACTIVE: 'This account is no longer active.',
  CSRF_REQUIRED: 'Your session is missing a security token. Refresh the page and try again.',
  CSRF_INVALID: 'Your session security check failed. Refresh the page and try again.',
  GOOGLE_TOKEN_INVALID: 'Google sign-in could not be verified. Please try again.',
  GOOGLE_EMAIL_UNVERIFIED: 'Your Google account email is not verified.',
  GOOGLE_EMAIL_MISSING: 'Your Google account has no email address.',
  ACCOUNT_DELETE_FAILED: 'Could not delete your account. Please try again.',
  MFA_FAILED: 'Two-step verification could not be completed. Please try again.',
  MFA_NOT_ENABLED: 'Two-step verification is not turned on for this account.',
  MFA_NO_BACKUP_CODES: 'There are no backup codes for this account.',
  MFA_SETUP_NOT_FOUND: 'There is no two-step verification setup in progress.',
  MFA_METHOD_NOT_FOUND: 'This verification method is not set up.',
  PASSWORD_RESET_FAILED: 'Could not reset your password. Please try again later.',
  RESET_EMAIL_FAILED: 'Could not send the reset email. Please try again later.',
  SESSION_SETUP_FAILED: 'Could not start your session. Please try again.',
  RESET_TOKEN_INVALID: 'This reset link is invalid or has expired. Request a new one.',
  SESSION_EXPIRED: 'Your session has expired. Please sign in again.',
  LINK_INVALID: 'This link is invalid or has expired.',
  VERIFICATION_TOKEN_INVALID:
    'This verification link is invalid or has expired. Request a new one.',
  VERIFICATION_CODE_INVALID: 'The verification code is incorrect. Please try again.',
  PASSWORD_CHANGE_NOT_REQUIRED: 'This account does not need a password change.',
  PASSWORD_POLICY:
    'Your password must be at least 12 characters and include an uppercase letter, a lowercase letter, a number and one of @$!%*?&.',
  PASSWORD_TOO_WEAK:
    'This password is too easy to guess. Try a longer phrase or a less common mix of words and characters.',
  EMAIL_NOT_VERIFIED: 'Please verify your email before signing in.',
  REFRESH_TOKEN_MISSING: 'Your session has expired. Please sign in again.',
  SESSION_NOT_FOUND: 'This session no longer exists.',
  TENANT_CONTEXT_MISSING: 'Your account is not linked to a business yet.',
  EMAIL_REQUIRED: 'Enter your email address.',
  VERIFICATION_SESSION_EXPIRED: 'Your verification session has expired. Please sign in again.',
  SIGN_IN_FAILED: 'Could not sign you in. Please try again.',
  FILE_DELETE_FAILED: 'Could not delete the file. Please try again.',
  FILE_TYPE_UNKNOWN: 'We could not recognise this file type.',
  FILE_URL_FAILED: 'Could not open the file. Please try again.',
  FILE_EMPTY: 'This file is empty.',
  FILE_TYPE_MISMATCH: 'This file’s content does not match its type.',
  FILE_NOT_FOUND: 'We could not find this file.',
  FILE_TOO_LARGE: 'This file is larger than {maxMb} MB.',
  FILE_TYPE_NOT_ALLOWED: 'This type of file is not allowed.',
  FILE_UPLOAD_FAILED: 'Could not upload the file. Please try again.',
  IMAGE_PROCESSING_FAILED: 'Could not process this image. Try another one.',
  FILE_REQUIRED: 'Choose a file to upload.',
  STORAGE_UNAVAILABLE: 'File storage is temporarily unavailable. Please try again later.',
  PRO_PLAN_REQUIRED: 'This feature needs a Pro subscription.',
  APP_UPDATE_REQUIRED: 'Please update the app to continue.',
  DONATION_FAILED: 'Could not record the donation. Please try again.',
  DONATION_STATS_FAILED: 'Could not load the donation figures. Please try again later.',
  ORDER_TOTAL_INVALID: 'The order total must be greater than zero.',
  DRIVER_CASH_CHANGED: 'The cash records changed while saving. Please try again.',
  DRIVER_PROFILE_NOT_FOUND: 'Your driver profile is not set up. Contact the TFTW team.',
  AMOUNT_ABOVE_ZERO: 'Enter an amount above zero.',
  AMOUNT_REQUIRED: 'Enter the amount handed over.',
  DRIVER_BUSY: 'Finish your current delivery before accepting another order.',
  DRIVER_NO_PENDING_RECOVERY: 'There is no failed delivery waiting for a decision.',
  DRIVER_ORDER_TAKEN: 'This order has already been taken by another driver.',
  DRIVER_ORDER_NOT_YOURS: 'This order is not assigned to you, or has moved on.',
  DRIVER_CASH_MISMATCH:
    'The amount collected does not match this order. Please check it and try again.',
  DRIVER_FLOAT_INSUFFICIENT: 'The driver only holds {amount} TND of float.',
  DRIVER_UNKNOWN: 'We could not find this driver.',
  DRIVER_MERCHANT_FAULT_RETURN:
    'When the merchant is at fault, return the food to the merchant and take the payment back.',
  DRIVER_ALREADY_COLLECTED:
    'You have already collected and paid for this order. Report a problem instead, so the food and the money are accounted for.',
  DRIVER_OFFLINE: 'Go online to accept orders.',
  DOCUMENT_ID_REQUIRED: 'Choose which additional document you mean.',
  DOCUMENT_TYPE_INVALID: 'This document type is not valid.',
  DOCUMENT_REQUIRED: 'Choose a document to upload.',
  DOCUMENTS_NOT_FOUND: 'No documents have been uploaded for this establishment.',
  DOCUMENT_PDF_ONLY: 'Legal documents must be PDF files.',
  LOCATION_ALREADY_REGISTERED:
    'This business location is already registered. If it is yours, contact support.',
  ESTABLISHMENT_LIMIT_REACHED:
    'You already have an establishment. Create an organization to add more locations.',
  INVALID_NUMBER: 'Enter a valid number.',
  ESTABLISHMENT_NOT_YOURS: 'You can only manage your own establishment.',
  FAVORITE_LIST_NAME_TAKEN: 'You already have a list with this name.',
  FAVORITE_LIST_NOT_FOUND: 'We could not find this list.',
  FAVORITE_NOT_FOUND: 'This favorite no longer exists.',
  FAVORITE_ALREADY_ADDED: 'This is already in your favorites.',
  FAVORITE_ALREADY_IN_LIST: 'This is already in the list.',
  INVALID_COORDINATES: 'This location is not valid.',
  ESTABLISHMENT_LOCATION_MISSING: 'This establishment has no location yet.',
  GEOCODING_FAILED: 'We could not look up this address. Please try again.',
  GEOCODING_UNAVAILABLE: 'Address search is temporarily unavailable. Please try again later.',
  SAVED_LOCATION_NOT_FOUND: 'We could not find this saved place.',
  LOCATION_PREFERENCES_NOT_FOUND: 'Your location settings could not be found.',
  STOCK_INSUFFICIENT: 'There is not enough stock left.',
  STOCK_RESERVATION_INVALID: 'The reserved stock does not match this change.',
  INVENTORY_ITEM_NOT_FOUND: 'We could not find this item in your stock.',
  LOYALTY_INSUFFICIENT_POINTS:
    'You do not have enough points. You have {available} points available.',
  LOYALTY_NOT_ENOUGH_POINTS: 'You do not have enough points for this.',
  LOYALTY_ACCOUNT_EXISTS: 'This account already has a loyalty account.',
  LOYALTY_ACCOUNT_NOT_FOUND: 'Your loyalty account is not set up yet.',
  CHALLENGE_NOT_ENDED: 'No challenge has ended yet, so there is no prize to claim.',
  LOYALTY_TIERS_MISSING: 'Loyalty levels are not set up.',
  REFERRER_NOT_FOUND: 'This referral link is not valid.',
  LEADERBOARD_NOT_LISTED: 'You are not on the leaderboard.',
  LEADERBOARD_CLAIM_GRAND_PRIZE:
    'You are in the top ranks: claim the grand prize instead of a discount.',
  MODERATION_CONFLICT: 'This cannot be applied: the account already has a conflicting action.',
  MODERATION_ACTION_NOT_FOUND: 'We could not find this moderation action.',
  MODERATION_RATE_LIMITED: 'Too many moderation actions. Try again in {seconds} seconds.',
  MODERATION_ACTION_NOT_ACTIVE: 'Only active actions can be revoked.',
  REPORT_RATE_LIMITED: 'You have sent too many reports. Try again in {seconds} seconds.',
  REPORT_NOT_FOUND: 'We could not find this report.',
  REPORT_NOT_ASSIGNED: 'This report is assigned to someone else.',
  MODERATION_NOT_OWNER: 'You can only change actions you created.',
  REPORT_DUPLICATE: 'You already reported this in the last 24 hours.',
  BULK_TOO_LARGE: 'Send to {max} recipients or fewer at a time.',
  SMS_OPT_OUT_FAILED: 'Could not update SMS preferences. Please try again.',
  INVALID_PHONE: 'Enter a valid phone number, for example +21612345678.',
  WEBHOOK_INVALID: 'This webhook request is not valid.',
  SMS_OPT_OUT_NOT_FOUND: 'There is no SMS opt-out for this number.',
  SMS_PAYLOAD_INVALID: 'An SMS needs a title and a message.',
  OFFER_SLOT_REQUIRED: 'Add at least one pickup time slot.',
  OFFER_START_IN_PAST: 'The start date cannot be in the past.',
  OFFER_END_BEFORE_START: 'The end date must be after the start date.',
  OFFER_HAS_RESERVATIONS:
    'This offer has active reservations. Wait for them to complete or cancel them first.',
  OFFER_DISCOUNT_OUT_OF_RANGE:
    'The discount must be between 40% and 90%. Your prices give {discount}%.',
  OFFER_PRICE_ORDER: 'The discounted price must be lower than the original price.',
  OFFER_SLOT_CAPACITY: 'Allow at least one order per time slot.',
  IMAGES_REQUIRED: 'Add at least one image.',
  OFFER_QUANTITY_UNAVAILABLE: 'There are not enough bags left.',
  OFFER_STATE_UNCHANGED: 'This offer is already in that state.',
  OFFER_PRICES_REQUIRED: 'Enter the original price and the discounted price.',
  OFFER_SLOT_ORDER: 'A pickup slot must start before it ends.',
  QUANTITY_ABOVE_ZERO: 'The quantity must be greater than zero.',
  OFFER_EXPIRED: 'This offer has expired.',
  OFFER_NOT_ACTIVE: 'This offer is not available right now.',
  OFFER_NOT_YOURS: 'You can only manage offers for your own establishment.',
  ORDER_NEEDS_OFFER: 'Add at least one offer to your order.',
  PICKUP_EXTENSION_NOT_ALLOWED: 'The pickup time cannot be extended for this order.',
  ORDER_INVALID_TRANSITION: 'This order cannot move from {from} to {to}.',
  CASH_PICKUP_ONLY:
    'Cash at the counter is only available for pickup. For delivery, pay the driver or pay online.',
  PAY_ON_DELIVERY_ONLY:
    'Pay on delivery is only available for delivery orders. For pickup, pay at the counter or online.',
  CUSTOMER_NOT_FOUND: 'We could not find this customer.',
  ORDER_CREATE_FAILED: 'Could not place your order. Please try again.',
  INVALID_GRANULARITY: 'Choose one of: {allowed}.',
  INVALID_GRANULARITY_VALUE: 'Choose a value between 1 and {max}.',
  PICKUP_CODE_INVALID: 'This pickup code is not valid.',
  PICKUP_QR_REQUIRED: 'Scan the customer’s QR code to confirm the pickup.',
  PICKUP_EXTENSION_NOT_FOUND: 'There is no extension request for this order.',
  ORDER_OFFERS_UNAVAILABLE: 'Some items in your order are no longer available.',
  PICKUP_MERCHANT_ONLY: 'Only the establishment can confirm this pickup.',
  PICKUP_OWNER_ONLY: 'Only the customer who placed this order can confirm the pickup.',
  ORDER_NOT_CANCELLABLE: 'This order can no longer be cancelled.',
  ORDER_ALREADY_CANCELLED: 'This order was already cancelled.',
  ORDER_NOT_LOCKED: 'This order is not locked.',
  ORDER_STATUS_NOT_SETTABLE:
    'The status {status} cannot be set directly. Use the matching order action.',
  ORDER_NOT_YOURS: 'You cannot manage this order.',
  INVITATION_ALREADY_PENDING: 'This email already has a pending invitation.',
  ORGANIZATION_LAST_ESTABLISHMENT:
    'An organization needs at least one establishment. Delete the organization instead.',
  ORGANIZATION_ESTABLISHMENT_NOT_FOUND: 'This establishment is not part of the organization.',
  ESTABLISHMENT_REQUIRED: 'Choose an establishment.',
  INVITATION_EXPIRED: 'This invitation has expired.',
  INVITATION_NOT_VALID: 'This invitation is no longer valid.',
  INVITATION_NOT_FOUND: 'We could not find this invitation.',
  INVITATION_NOT_PENDING: 'Only pending invitations can be revoked.',
  ORGANIZATION_OWNER_ONLY: 'Only the organization owner can do this.',
  ORGANIZATION_NOT_FOUND: 'We could not find this organization.',
  ORGANIZATION_ESTABLISHMENT_MISMATCH: 'This establishment does not belong to the organization.',
  ORGANIZATION_ESTABLISHMENT_EXISTS: 'This establishment is already part of the organization.',
  ORGANIZATION_LIMIT_REACHED: 'You already have an organization. Each merchant can have one.',
  ORGANIZATION_NOT_YOURS: 'You can only view your own organization.',
  PAYOUT_ALREADY_RUNNING:
    'A payout is already running. Wait for it to finish before starting another.',
  ORDER_NOT_AWAITING_PAYMENT: 'This order is not waiting for a payment.',
  PAYMENT_NOT_FOUND: 'We could not find this payment.',
  PAYMENT_ALREADY_SUCCEEDED: 'Your previous payment went through. Your order has been updated.',
  PAYMENT_VERIFY_FAILED: 'We could not check the payment status. Please try again.',
  MERCHANT_NOT_FOUND: 'We could not find this merchant.',
  PAYMENT_AMOUNT_INVALID: 'The payment amount is not valid.',
  PAYMENT_FAILED: 'The payment could not be started. Please try again.',
  PAYMENT_UNAVAILABLE: 'Online payment is temporarily unavailable. Please try again later.',
  SUBSCRIPTION_NOT_YOURS: 'You can only manage the subscription of your own establishment.',
  SUBSCRIPTION_RENEW_TOO_EARLY:
    'Your subscription is active for {days} more days. You can renew when fewer than 7 days remain.',
  COMMUNITY_FUND_NO_ESTABLISHMENT:
    'We could not find the establishment linked to your account, so there is no community fund to show yet.',
  REVIEW_NOT_YOURS: 'You can only change your own reviews.',
  REVIEW_RESPONSE_NOT_ALLOWED: 'You can only respond to reviews of your own establishment.',
  REVIEW_ORDER_NOT_COMPLETED: 'You can review an order once you have collected it.',
  REVIEW_ORDER_NOT_YOURS: 'You can only review your own orders.',
  REVIEW_TOO_OLD: 'Reviews can only be edited within 30 days.',
  REVIEW_ESTABLISHMENT_INACTIVE: 'This establishment is not active, so it cannot be reviewed.',
  REVIEW_OWN_ESTABLISHMENT: 'You cannot review your own establishment.',
  REVIEW_FAILED: 'Could not save the review. Please try again.',
  REVIEWS_LOAD_FAILED: 'Could not load the reviews. Please try again.',
  REVIEW_OFFER_MISMATCH: 'This offer does not belong to the establishment you are reviewing.',
  REVIEW_NOT_FOUND: 'We could not find this review.',
  REVIEWER_INACTIVE: 'This account cannot post reviews.',
  REVIEW_ALREADY_REPORTED: 'You have already reported this review.',
  REVIEW_ALREADY_RESPONDED: 'You have already responded to this review.',
  REVIEW_ALREADY_EXISTS: 'You have already reviewed this order.',
  PASSWORD_OAUTH_ACCOUNT: 'This account signs in with Google, so it has no password to set.',
  CURRENT_PASSWORD_INCORRECT: 'Your current password is incorrect.',
  FIRST_NAME_REQUIRED: 'Enter your first name.',
  LAST_NAME_REQUIRED: 'Enter your last name.',
  PASSWORD_REQUIRED: 'Enter your password.',
  VERIFICATION_SEND_FAILED: 'Could not send the verification code. Please try again.',
  INVALID_SETTING: 'This setting is not valid.',
  MAX_DISTANCE_RANGE: 'Choose a distance between 100 m and 50 km.',
  VERIFICATION_ATTEMPTS_EXCEEDED: 'Too many attempts. Request a new code.',
  MIN_DISCOUNT_RANGE: 'Choose a minimum discount between 0% and 100%.',
  CONSENT_NOT_FOUND: 'There is no active consent of this type.',
  VERIFICATION_CODE_MISSING: 'Request a verification code first.',
  PHONE_MISMATCH: 'This phone number does not match the one being verified.',
  PHONE_VERIFICATION_UNAVAILABLE:
    'Phone verification is temporarily unavailable. Please try again later.',
  ACCOUNT_CREATE_FAILED: 'Could not create your account. Please try again.',
  USER_NOT_DELETED: 'This account is not deleted.',
  VERIFICATION_CODE_EXPIRED: 'This code has expired. Request a new one.',
  BALLOT_NOT_OPEN: 'Voting is not open right now.',
  BALLOT_CLOSED: 'Voting has closed.',
  NOT_ELIGIBLE: 'You are not eligible to vote in this round.',
  ALREADY_VOTED: 'You have already voted in this round.',
  INVALID_PRIZE: 'This prize is not part of the vote.',
  SNAPSHOT_NOT_READY: 'Voting is being prepared. Please try again in a few minutes.',
  NO_ACTIVE_CYCLE: 'There is no community vote right now.',
  FIELD_LOCKED_AFTER_ACTIVATION: 'This can no longer be changed: the vote has started.',
  VOTE_FIRST_TO_SEE_RESULTS: 'Vote first to see the results.',
  VOTING_CYCLE_EXISTS: 'Another vote is already running.',
  VOTING_CYCLE_CHANGED: 'This vote changed while you were editing it. Refresh and try again.',
  VOTING_CYCLE_INVALID_STATE: 'This action is not available while the vote is {status}.',
  VOTING_CLAIM_FINAL: 'This prize claim is closed and can no longer be changed.',
  VOTING_CYCLE_NOT_DRAFT: 'Only a draft vote can be changed this way.',
  VOTING_NO_COMPLETED_CYCLE: 'No completed vote has a prize to claim yet.',
  VOTING_PRIZE_TOP_ONLY: 'Only the top {count} on the leaderboard can claim this prize.',
  VOTING_CLAIM_NOT_FOUND: 'We could not find this prize claim.',
  VOTING_SNAPSHOT_RETRY_INVALID:
    'The voter list can only be rebuilt while voting is open and not yet ready.',
  VOTING_CYCLE_NOT_FOUND: 'We could not find this vote.',
  VOTING_PRIZE_ALREADY_CLAIMED: 'You have already claimed your prize for this vote.',
  VALIDATION_FAILED: 'Some details are not valid. Check them and try again.',
  VALIDATION_REQUIRED: 'This field is required.',
  VALIDATION_EMAIL: 'Enter a valid email address.',
  VALIDATION_MIN_LENGTH: 'Enter at least {min} characters.',
  VALIDATION_MAX_LENGTH: 'Enter at most {max} characters.',
  VALIDATION_LENGTH: 'Enter between {min} and {max} characters.',
  VALIDATION_MIN: 'Enter a value of at least {min}.',
  VALIDATION_MAX: 'Enter a value of at most {max}.',
  VALIDATION_NUMBER: 'Enter a number.',
  VALIDATION_INTEGER: 'Enter a whole number.',
  VALIDATION_POSITIVE: 'Enter a number above zero.',
  VALIDATION_BOOLEAN: 'Choose yes or no.',
  VALIDATION_DATE: 'Enter a valid date.',
  VALIDATION_ENUM: 'Choose one of the available options.',
  VALIDATION_FORMAT: 'This is not in the expected format.',
  VALIDATION_PHONE: 'Enter a valid phone number, for example +21612345678.',
  VALIDATION_URL: 'Enter a valid link.',
  VALIDATION_ID: 'This identifier is not valid.',
  VALIDATION_TEXT: 'Enter text.',
  VALIDATION_LIST: 'This must be a list.',
  VALIDATION_LIST_MIN: 'Add at least {min} items.',
  VALIDATION_LIST_MAX: 'Add at most {max} items.',
  VALIDATION_COORDINATE: 'This location is not valid.',
  VALIDATION_NOT_ALLOWED: 'This field is not allowed.',
  VALIDATION_INVALID: 'This value is not valid.',
  ACCOUNT_LOCKED: 'Too many failed attempts. Your account is locked for now; try again later.',
  INVALID_CREDENTIALS: 'The email or password is incorrect.',
  LOGIN_TEMPORARILY_BLOCKED: 'Too many sign-in attempts. Please wait and try again later.',
  ACCOUNT_SUSPENDED: 'This account is suspended. Contact support for help.',
  PASSWORD_REUSED: 'Choose a password you have not used in your last {count} passwords.',
  EMAIL_VERIFICATION_FAILED: 'We could not verify your email. Please try again.',
  VERIFICATION_RESEND_FAILED: 'Could not send the verification email. Please try again.',
  QUERY_TOO_COMPLEX: 'This search is too complex. Simplify the filters and try again.',
  TRIAL_EXPIRED: 'Your subscription has expired. Renew it to continue.',
  OFFER_SLOT_CAPACITY_EXCEEDED:
    'Your pickup slots allow {capacity} orders but only {quantity} bags are available. Lower the orders per slot or add bags.',
  OFFER_CANNOT_REACTIVATE: 'Only expired, cancelled or sold-out offers can be reactivated.',
  OFFER_CANNOT_TOGGLE: 'Only active or draft offers can be turned on or off.',
  ESTABLISHMENT_PENDING_APPROVAL:
    'Your establishment is waiting for approval. You can publish offers once our team has approved it.',
  ESTABLISHMENT_SUSPENDED:
    'Your establishment is suspended, so offers cannot be published. Contact support.',
  ESTABLISHMENT_REJECTED:
    'Your establishment was not approved, so offers cannot be published. Contact support to find out why.',
  ESTABLISHMENT_INACTIVE: 'Your establishment is inactive. Reactivate it before publishing offers.',
  PHONE_VERIFICATION_REQUIRED: 'Add your phone number to place an order.',
  INSUFFICIENT_STOCK: 'Some items in your order are no longer available.',
  PICKUP_LOCKED: 'Pickup is locked after too many wrong codes. Contact support.',
  ORDER_NOT_READY: 'This order is not ready for pickup yet. Wait for the merchant to confirm it.',
  CODE_EXPIRED: 'This pickup code has expired: the pickup window has ended.',
  PICKUP_ALREADY_DONE: 'This pickup has already been confirmed.',
  CANCELLATION_WINDOW_CLOSED: 'Orders cannot be cancelled in the hour before pickup.',
  PAYMENT_METHOD_UNSUPPORTED: 'This payment method is not available. Please pay in cash or online.',
  ESTABLISHMENT_CREATE_FAILED: 'Could not create the establishment. Please try again.',
  USER_LOAD_FAILED: 'Could not load this account. Please try again.',
  PROFILE_UPDATE_FAILED: 'Could not update the profile. Please try again.',
  LOCATION_UPDATE_FAILED: 'Could not update the location. Please try again.',
  USER_STATUS_UPDATE_FAILED: 'Could not change the account status. Please try again.',
  PHONE_VERIFICATION_FAILED: 'Could not verify your phone number. Please try again.',
  LOCATION_PREFERENCES_FAILED: 'Could not load or save your location settings. Please try again.',
  PRIVACY_REQUEST_FAILED: 'Could not save your privacy choice. Please try again.',
  PRIVACY_EXPORT_FAILED: 'Could not export your data. Please try again.',
  PRIVACY_DELETION_FAILED: 'Could not process the deletion request. Please try again.',
  CHALLENGE_PRIZE_ALREADY_CLAIMED: 'You have already claimed your prize for this challenge.',
} as const;

export type ErrorCode = keyof typeof EN;
