import type { ErrorCode } from './en';

/** Error messages, French. Keys and placeholders mirror `en.ts`. */
export const FR: Readonly<Record<ErrorCode, string>> = {
  BAD_REQUEST: 'Cette demande n’a pas pu être traitée.',
  UNAUTHORIZED: 'Veuillez vous connecter pour continuer.',
  FORBIDDEN: 'Vous n’avez pas l’autorisation de faire cela.',
  NOT_FOUND: 'Nous n’avons pas trouvé ce que vous cherchez.',
  ROUTE_NOT_FOUND: 'Cette page ou action n’existe pas.',
  METHOD_NOT_ALLOWED: 'Cette action n’est pas autorisée ici.',
  CONFLICT: 'Cela entre en conflit avec l’état actuel. Actualisez et réessayez.',
  GONE: 'Ce n’est plus disponible.',
  PAYLOAD_TOO_LARGE: 'Ce que vous avez envoyé est trop volumineux.',
  UNPROCESSABLE: 'Impossible de traiter cette demande. Vérifiez les informations et réessayez.',
  TOO_MANY_REQUESTS: 'Trop de tentatives. Patientez un instant puis réessayez.',
  INTERNAL_ERROR: 'Un problème est survenu de notre côté. Veuillez réessayer.',
  INTERNAL_ERROR_WITH_ID:
    'Un problème est survenu de notre côté. Si cela persiste, contactez le support avec l’identifiant de l’erreur.',
  SERVICE_UNAVAILABLE: 'Ce service est temporairement indisponible. Veuillez réessayer plus tard.',
  TIMEOUT: 'Cela a pris trop de temps. Veuillez réessayer.',
  ACCESS_DENIED: 'Vous n’avez pas accès à ceci.',
  AUTH_REQUIRED: 'Veuillez vous connecter pour continuer.',
  ADMIN_REQUIRED: 'Seuls les administrateurs peuvent faire cela.',
  MODERATOR_REQUIRED: 'Seuls les administrateurs et modérateurs peuvent faire cela.',
  INVALID_ID: 'Ce lien ou identifiant n’est pas valide.',
  INVALID_DATE: 'Saisissez une date valide.',
  DATE_RANGE_REQUIRED: 'Choisissez une date de début et une date de fin.',
  DATE_RANGE_ORDER: 'La date de début doit précéder la date de fin.',
  DATE_RANGE_TOO_LONG: 'Choisissez une période de {maxDays} jours maximum.',
  INVALID_PERIOD: 'Choisissez une de ces périodes : {allowed}.',
  INVALID_PAGINATION: 'Cette demande de page n’est pas valide.',
  LIMIT_TOO_HIGH: 'Vous avez demandé trop de résultats à la fois.',
  INVALID_EXPORT_FORMAT: 'Choisissez JSON ou CSV.',
  INVALID_STATUS: 'Choisissez un de ces statuts : {allowed}.',
  INVALID_FILTERS: 'Ces filtres ne sont pas valides : {details}',
  RATE_LIMITED: 'Trop de tentatives. Réessayez dans {seconds} secondes.',
  EMAIL_ALREADY_REGISTERED: 'Un compte existe déjà avec cette adresse e-mail.',
  PHONE_ALREADY_REGISTERED: 'Ce numéro est déjà associé à un autre compte.',
  USER_ALREADY_EXISTS: 'Un compte avec ces informations existe déjà.',
  USER_NOT_FOUND: 'Nous n’avons pas trouvé ce compte.',
  RESOURCE_NOT_FOUND: 'Nous n’avons pas trouvé cet élément.',
  REFUND_ALREADY_REQUESTED: 'Un remboursement a déjà été demandé pour cette commande.',
  ZONE_NAME_TAKEN: 'Une zone portant ce nom existe déjà.',
  ADMIN_CONTEXT_MISSING: 'Votre session administrateur est incomplète. Reconnectez-vous.',
  ANNOUNCEMENT_NOT_FOUND: 'Cette annonce n’existe plus.',
  ORDER_CANNOT_BE_CANCELLED: 'Cette commande ne peut plus être annulée.',
  ORDER_NOT_REFUNDABLE:
    'Cette commande ne peut pas être remboursée dans son état de paiement actuel.',
  CONFIG_INVALID: 'Cette configuration n’est pas valide : {details}',
  CONFIG_IMPORT_INVALID: 'La configuration importée n’est pas valide : {details}',
  CONFIG_IMPORT_NOT_OBJECT: 'Le fichier importé n’est pas une configuration valide.',
  CONFIG_VERSION_NOT_FOUND: 'La version {version} de la configuration n’existe pas.',
  CONFIG_NOT_FOUND: 'Aucune configuration système active.',
  DAYS_OUT_OF_RANGE: 'Choisissez entre 1 et 365 jours.',
  HOURS_OUT_OF_RANGE: 'Choisissez entre 1 et 168 heures (7 jours).',
  DELETED_OFFER_NOT_FOUND: 'Cette offre supprimée n’existe plus.',
  DRIVER_NOT_FOUND: 'Nous n’avons pas trouvé ce livreur.',
  TRIAL_EXTENSION_REQUIRED:
    'Indiquez une nouvelle fin d’essai ou un nombre de jours de prolongation.',
  TRIAL_END_IN_PAST: 'La fin de l’essai doit être dans le futur.',
  ESTABLISHMENT_NOT_FOUND: 'Nous n’avons pas trouvé cet établissement.',
  AUDIT_LOGS_FAILED: 'Impossible de charger le journal d’audit. Réessayez plus tard.',
  ANALYTICS_FAILED: 'Impossible de charger ces chiffres. Réessayez plus tard.',
  GEOZONE_NOT_FOUND: 'Nous n’avons pas trouvé cette zone.',
  ORDER_NOT_FOUND: 'Nous n’avons pas trouvé cette commande.',
  CASH_REFUND_NOT_COMPLETED:
    'Seule une commande en espèces terminée peut être remboursée. Annulez plutôt la commande.',
  TEAM_MEMBER_NOT_FOUND: 'Nous n’avons pas trouvé ce membre de l’équipe.',
  TEAM_ROLE_NOT_EDITABLE:
    'Seuls les membres administrateurs et modérateurs peuvent être modifiés ici.',
  TEAM_NOT_MEMBER: 'Cette personne ne fait pas partie de l’équipe.',
  TEAM_CANNOT_REMOVE_SELF: 'Vous ne pouvez pas vous retirer de l’équipe.',
  ESTABLISHMENT_NOT_PENDING:
    'Seuls les établissements en attente peuvent être approuvés ou refusés.',
  REASON_REQUIRED: 'Indiquez la raison de cette action.',
  ORDER_ALREADY_REFUNDED: 'Cette commande a déjà été remboursée.',
  TICKET_NOT_FOUND: 'Nous n’avons pas trouvé ce ticket.',
  UNKNOWN_BULK_ACTION: 'Cette action groupée n’est pas prise en charge : {action}',
  OFFER_NOT_FOUND: 'Cette offre n’est plus disponible.',
  DASHBOARD_TOO_MANY_WIDGETS: 'Un tableau de bord peut contenir 20 widgets au maximum.',
  DASHBOARD_NO_WIDGETS: 'Ajoutez au moins un widget.',
  DASHBOARD_NOT_FOUND: 'Nous n’avons pas trouvé ce tableau de bord.',
  DASHBOARD_NAME_TAKEN: 'Un tableau de bord porte déjà ce nom.',
  DASHBOARD_FORBIDDEN: 'Vous n’avez pas l’autorisation de modifier ce tableau de bord.',
  DASHBOARD_TEMPLATE_NOT_FOUND:
    'Ce modèle de tableau de bord n’est pas disponible pour votre compte.',
  DASHBOARD_TEMPLATE_INVALID: 'Ce modèle de tableau de bord est mal configuré.',
  WIDGET_NOT_FOUND: 'Nous n’avons pas trouvé ce widget.',
  WIDGET_POSITION_CONFLICT: 'Un autre widget occupe déjà la ligne {row}, colonne {column}.',
  WIDGET_POSITION_START: 'Les widgets commencent à la ligne 1, colonne 1.',
  WIDGET_HEIGHT_RANGE: 'Un widget fait de 1 à 6 lignes de haut.',
  WIDGET_WIDTH_RANGE: 'Un widget fait de 1 à 12 colonnes de large.',
  INVALID_ROLE: 'Ce rôle n’est pas valide.',
  ACCESS_BLOCKED_SUSPICIOUS: 'L’accès est temporairement bloqué en raison d’une activité suspecte.',
  ACCOUNT_ALREADY_VERIFIED: 'Ce compte est déjà vérifié.',
  ACCOUNT_INACTIVE: 'Ce compte n’est plus actif.',
  CSRF_REQUIRED: 'Il manque un jeton de sécurité à votre session. Actualisez la page et réessayez.',
  CSRF_INVALID:
    'La vérification de sécurité de votre session a échoué. Actualisez la page et réessayez.',
  GOOGLE_TOKEN_INVALID: 'La connexion Google n’a pas pu être vérifiée. Veuillez réessayer.',
  GOOGLE_EMAIL_UNVERIFIED: 'L’adresse e-mail de votre compte Google n’est pas vérifiée.',
  GOOGLE_EMAIL_MISSING: 'Votre compte Google n’a pas d’adresse e-mail.',
  ACCOUNT_DELETE_FAILED: 'Impossible de supprimer votre compte. Veuillez réessayer.',
  MFA_FAILED: 'La vérification en deux étapes n’a pas abouti. Veuillez réessayer.',
  MFA_NOT_ENABLED: 'La vérification en deux étapes n’est pas activée pour ce compte.',
  MFA_NO_BACKUP_CODES: 'Il n’y a pas de codes de secours pour ce compte.',
  MFA_SETUP_NOT_FOUND: 'Aucune configuration de vérification en deux étapes n’est en cours.',
  MFA_METHOD_NOT_FOUND: 'Cette méthode de vérification n’est pas configurée.',
  PASSWORD_RESET_FAILED: 'Impossible de réinitialiser votre mot de passe. Réessayez plus tard.',
  RESET_EMAIL_FAILED: 'Impossible d’envoyer l’e-mail de réinitialisation. Réessayez plus tard.',
  SESSION_SETUP_FAILED: 'Impossible de démarrer votre session. Veuillez réessayer.',
  RESET_TOKEN_INVALID:
    'Ce lien de réinitialisation est invalide ou a expiré. Demandez-en un nouveau.',
  SESSION_EXPIRED: 'Votre session a expiré. Veuillez vous reconnecter.',
  LINK_INVALID: 'Ce lien est invalide ou a expiré.',
  VERIFICATION_TOKEN_INVALID:
    'Ce lien de vérification est invalide ou a expiré. Demandez-en un nouveau.',
  VERIFICATION_CODE_INVALID: 'Le code de vérification est incorrect. Veuillez réessayer.',
  PASSWORD_CHANGE_NOT_REQUIRED: 'Ce compte n’a pas besoin de changer de mot de passe.',
  PASSWORD_POLICY:
    'Votre mot de passe doit contenir au moins 12 caractères, avec une majuscule, une minuscule, un chiffre et un de ces caractères : @$!%*?&.',
  PASSWORD_TOO_WEAK:
    'Ce mot de passe est trop facile à deviner. Essayez une phrase plus longue ou un mélange moins courant de mots et de caractères.',
  EMAIL_NOT_VERIFIED: 'Veuillez vérifier votre adresse e-mail avant de vous connecter.',
  REFRESH_TOKEN_MISSING: 'Votre session a expiré. Veuillez vous reconnecter.',
  SESSION_NOT_FOUND: 'Cette session n’existe plus.',
  TENANT_CONTEXT_MISSING: 'Votre compte n’est pas encore rattaché à une entreprise.',
  EMAIL_REQUIRED: 'Saisissez votre adresse e-mail.',
  VERIFICATION_SESSION_EXPIRED:
    'Votre session de vérification a expiré. Veuillez vous reconnecter.',
  SIGN_IN_FAILED: 'Impossible de vous connecter. Veuillez réessayer.',
  FILE_DELETE_FAILED: 'Impossible de supprimer le fichier. Veuillez réessayer.',
  FILE_TYPE_UNKNOWN: 'Nous n’avons pas reconnu ce type de fichier.',
  FILE_URL_FAILED: 'Impossible d’ouvrir le fichier. Veuillez réessayer.',
  FILE_EMPTY: 'Ce fichier est vide.',
  FILE_TYPE_MISMATCH: 'Le contenu de ce fichier ne correspond pas à son type.',
  FILE_NOT_FOUND: 'Nous n’avons pas trouvé ce fichier.',
  FILE_TOO_LARGE: 'Ce fichier dépasse {maxMb} Mo.',
  FILE_TYPE_NOT_ALLOWED: 'Ce type de fichier n’est pas autorisé.',
  FILE_UPLOAD_FAILED: 'Impossible d’envoyer le fichier. Veuillez réessayer.',
  IMAGE_PROCESSING_FAILED: 'Impossible de traiter cette image. Essayez-en une autre.',
  FILE_REQUIRED: 'Choisissez un fichier à envoyer.',
  STORAGE_UNAVAILABLE:
    'Le stockage de fichiers est temporairement indisponible. Réessayez plus tard.',
  PRO_PLAN_REQUIRED: 'Cette fonctionnalité nécessite un abonnement Pro.',
  APP_UPDATE_REQUIRED: 'Veuillez mettre à jour l’application pour continuer.',
  DONATION_FAILED: 'Impossible d’enregistrer le don. Veuillez réessayer.',
  DONATION_STATS_FAILED: 'Impossible de charger les chiffres des dons. Réessayez plus tard.',
  ORDER_TOTAL_INVALID: 'Le total de la commande doit être supérieur à zéro.',
  DRIVER_CASH_CHANGED:
    'Les données d’espèces ont changé pendant l’enregistrement. Veuillez réessayer.',
  DRIVER_PROFILE_NOT_FOUND: 'Votre profil de livreur n’est pas configuré. Contactez l’équipe TFTW.',
  AMOUNT_ABOVE_ZERO: 'Saisissez un montant supérieur à zéro.',
  AMOUNT_REQUIRED: 'Saisissez le montant remis.',
  DRIVER_BUSY: 'Terminez votre livraison en cours avant d’accepter une autre commande.',
  DRIVER_NO_PENDING_RECOVERY: 'Aucune livraison échouée n’attend de décision.',
  DRIVER_ORDER_TAKEN: 'Cette commande a déjà été prise par un autre livreur.',
  DRIVER_ORDER_NOT_YOURS: 'Cette commande ne vous est pas attribuée, ou a déjà avancé.',
  DRIVER_CASH_MISMATCH:
    'Le montant encaissé ne correspond pas à cette commande. Vérifiez-le et réessayez.',
  DRIVER_FLOAT_INSUFFICIENT: 'Le livreur ne détient que {amount} TND de fonds de caisse.',
  DRIVER_UNKNOWN: 'Nous n’avons pas trouvé ce livreur.',
  DRIVER_MERCHANT_FAULT_RETURN:
    'Si le commerçant est en faute, rendez-lui la nourriture et récupérez le paiement.',
  DRIVER_ALREADY_COLLECTED:
    'Vous avez déjà récupéré et payé cette commande. Signalez plutôt un problème, pour que la nourriture et l’argent soient comptabilisés.',
  DRIVER_OFFLINE: 'Passez en ligne pour accepter des commandes.',
  DOCUMENT_ID_REQUIRED: 'Précisez de quel document supplémentaire il s’agit.',
  DOCUMENT_TYPE_INVALID: 'Ce type de document n’est pas valide.',
  DOCUMENT_REQUIRED: 'Choisissez un document à envoyer.',
  DOCUMENTS_NOT_FOUND: 'Aucun document n’a été envoyé pour cet établissement.',
  DOCUMENT_PDF_ONLY: 'Les documents légaux doivent être au format PDF.',
  LOCATION_ALREADY_REGISTERED:
    'Cette adresse commerciale est déjà enregistrée. Si c’est la vôtre, contactez le support.',
  ESTABLISHMENT_LIMIT_REACHED:
    'Vous avez déjà un établissement. Créez une organisation pour ajouter d’autres adresses.',
  INVALID_NUMBER: 'Saisissez un nombre valide.',
  ESTABLISHMENT_NOT_YOURS: 'Vous ne pouvez gérer que votre propre établissement.',
  FAVORITE_LIST_NAME_TAKEN: 'Vous avez déjà une liste portant ce nom.',
  FAVORITE_LIST_NOT_FOUND: 'Nous n’avons pas trouvé cette liste.',
  FAVORITE_NOT_FOUND: 'Ce favori n’existe plus.',
  FAVORITE_ALREADY_ADDED: 'C’est déjà dans vos favoris.',
  FAVORITE_ALREADY_IN_LIST: 'C’est déjà dans cette liste.',
  INVALID_COORDINATES: 'Cette position n’est pas valide.',
  ESTABLISHMENT_LOCATION_MISSING: 'Cet établissement n’a pas encore de position.',
  GEOCODING_FAILED: 'Impossible de trouver cette adresse. Veuillez réessayer.',
  GEOCODING_UNAVAILABLE:
    'La recherche d’adresse est temporairement indisponible. Réessayez plus tard.',
  SAVED_LOCATION_NOT_FOUND: 'Nous n’avons pas trouvé ce lieu enregistré.',
  LOCATION_PREFERENCES_NOT_FOUND: 'Vos paramètres de localisation sont introuvables.',
  STOCK_INSUFFICIENT: 'Il ne reste pas assez de stock.',
  STOCK_RESERVATION_INVALID: 'Le stock réservé ne correspond pas à cette modification.',
  INVENTORY_ITEM_NOT_FOUND: 'Nous n’avons pas trouvé cet article dans votre stock.',
  LOYALTY_INSUFFICIENT_POINTS:
    'Vous n’avez pas assez de points. Vous avez {available} points disponibles.',
  LOYALTY_NOT_ENOUGH_POINTS: 'Vous n’avez pas assez de points pour cela.',
  LOYALTY_ACCOUNT_EXISTS: 'Ce compte a déjà un compte fidélité.',
  LOYALTY_ACCOUNT_NOT_FOUND: 'Votre compte fidélité n’est pas encore créé.',
  CHALLENGE_NOT_ENDED: 'Aucun défi n’est encore terminé : il n’y a pas de prix à réclamer.',
  LOYALTY_TIERS_MISSING: 'Les niveaux de fidélité ne sont pas configurés.',
  REFERRER_NOT_FOUND: 'Ce lien de parrainage n’est pas valide.',
  LEADERBOARD_NOT_LISTED: 'Vous n’êtes pas dans le classement.',
  LEADERBOARD_CLAIM_GRAND_PRIZE:
    'Vous êtes dans le haut du classement : réclamez le grand prix plutôt qu’une réduction.',
  MODERATION_CONFLICT: 'Impossible d’appliquer : le compte a déjà une action incompatible.',
  MODERATION_ACTION_NOT_FOUND: 'Nous n’avons pas trouvé cette action de modération.',
  MODERATION_RATE_LIMITED: 'Trop d’actions de modération. Réessayez dans {seconds} secondes.',
  MODERATION_ACTION_NOT_ACTIVE: 'Seules les actions actives peuvent être révoquées.',
  REPORT_RATE_LIMITED: 'Vous avez envoyé trop de signalements. Réessayez dans {seconds} secondes.',
  REPORT_NOT_FOUND: 'Nous n’avons pas trouvé ce signalement.',
  REPORT_NOT_ASSIGNED: 'Ce signalement est attribué à quelqu’un d’autre.',
  MODERATION_NOT_OWNER: 'Vous ne pouvez modifier que les actions que vous avez créées.',
  REPORT_DUPLICATE: 'Vous avez déjà signalé ceci au cours des dernières 24 heures.',
  BULK_TOO_LARGE: 'Envoyez à {max} destinataires au maximum à la fois.',
  SMS_OPT_OUT_FAILED: 'Impossible de mettre à jour les préférences SMS. Veuillez réessayer.',
  INVALID_PHONE: 'Saisissez un numéro valide, par exemple +21612345678.',
  WEBHOOK_INVALID: 'Cette requête webhook n’est pas valide.',
  SMS_OPT_OUT_NOT_FOUND: 'Aucune désinscription SMS pour ce numéro.',
  SMS_PAYLOAD_INVALID: 'Un SMS doit avoir un titre et un message.',
  OFFER_SLOT_REQUIRED: 'Ajoutez au moins un créneau de retrait.',
  OFFER_START_IN_PAST: 'La date de début ne peut pas être dans le passé.',
  OFFER_END_BEFORE_START: 'La date de fin doit être après la date de début.',
  OFFER_HAS_RESERVATIONS:
    'Cette offre a des réservations en cours. Attendez qu’elles se terminent ou annulez-les d’abord.',
  OFFER_DISCOUNT_OUT_OF_RANGE:
    'La réduction doit être comprise entre 40% et 90%. Vos prix donnent {discount}%.',
  OFFER_PRICE_ORDER: 'Le prix réduit doit être inférieur au prix d’origine.',
  OFFER_SLOT_CAPACITY: 'Autorisez au moins une commande par créneau.',
  IMAGES_REQUIRED: 'Ajoutez au moins une image.',
  OFFER_QUANTITY_UNAVAILABLE: 'Il ne reste pas assez de paniers.',
  OFFER_STATE_UNCHANGED: 'Cette offre est déjà dans cet état.',
  OFFER_PRICES_REQUIRED: 'Saisissez le prix d’origine et le prix réduit.',
  OFFER_SLOT_ORDER: 'Un créneau de retrait doit commencer avant de finir.',
  QUANTITY_ABOVE_ZERO: 'La quantité doit être supérieure à zéro.',
  OFFER_EXPIRED: 'Cette offre a expiré.',
  OFFER_NOT_ACTIVE: 'Cette offre n’est pas disponible pour le moment.',
  OFFER_NOT_YOURS: 'Vous ne pouvez gérer que les offres de votre établissement.',
  ORDER_NEEDS_OFFER: 'Ajoutez au moins une offre à votre commande.',
  PICKUP_EXTENSION_NOT_ALLOWED:
    'L’heure de retrait ne peut pas être prolongée pour cette commande.',
  ORDER_INVALID_TRANSITION: 'Cette commande ne peut pas passer de {from} à {to}.',
  CASH_PICKUP_ONLY:
    'Le paiement en espèces au comptoir est réservé au retrait. Pour la livraison, payez le livreur ou en ligne.',
  PAY_ON_DELIVERY_ONLY:
    'Le paiement à la livraison est réservé aux commandes livrées. Pour le retrait, payez au comptoir ou en ligne.',
  CUSTOMER_NOT_FOUND: 'Nous n’avons pas trouvé ce client.',
  ORDER_CREATE_FAILED: 'Impossible de passer votre commande. Veuillez réessayer.',
  INVALID_GRANULARITY: 'Choisissez parmi : {allowed}.',
  INVALID_GRANULARITY_VALUE: 'Choisissez une valeur entre 1 et {max}.',
  PICKUP_CODE_INVALID: 'Ce code de retrait n’est pas valide.',
  PICKUP_QR_REQUIRED: 'Scannez le code QR du client pour confirmer le retrait.',
  PICKUP_EXTENSION_NOT_FOUND: 'Aucune demande de prolongation pour cette commande.',
  ORDER_OFFERS_UNAVAILABLE: 'Certains articles de votre commande ne sont plus disponibles.',
  PICKUP_MERCHANT_ONLY: 'Seul l’établissement peut confirmer ce retrait.',
  PICKUP_OWNER_ONLY: 'Seul le client qui a passé la commande peut confirmer le retrait.',
  ORDER_NOT_CANCELLABLE: 'Cette commande ne peut plus être annulée.',
  ORDER_ALREADY_CANCELLED: 'Cette commande a déjà été annulée.',
  ORDER_NOT_LOCKED: 'Cette commande n’est pas verrouillée.',
  ORDER_STATUS_NOT_SETTABLE:
    'Le statut {status} ne peut pas être défini directement. Utilisez l’action correspondante.',
  ORDER_NOT_YOURS: 'Vous ne pouvez pas gérer cette commande.',
  INVITATION_ALREADY_PENDING: 'Cette adresse a déjà une invitation en attente.',
  ORGANIZATION_LAST_ESTABLISHMENT:
    'Une organisation doit garder au moins un établissement. Supprimez plutôt l’organisation.',
  ORGANIZATION_ESTABLISHMENT_NOT_FOUND: 'Cet établissement ne fait pas partie de l’organisation.',
  ESTABLISHMENT_REQUIRED: 'Choisissez un établissement.',
  INVITATION_EXPIRED: 'Cette invitation a expiré.',
  INVITATION_NOT_VALID: 'Cette invitation n’est plus valide.',
  INVITATION_NOT_FOUND: 'Nous n’avons pas trouvé cette invitation.',
  INVITATION_NOT_PENDING: 'Seules les invitations en attente peuvent être révoquées.',
  ORGANIZATION_OWNER_ONLY: 'Seul le propriétaire de l’organisation peut faire cela.',
  ORGANIZATION_NOT_FOUND: 'Nous n’avons pas trouvé cette organisation.',
  ORGANIZATION_ESTABLISHMENT_MISMATCH: 'Cet établissement n’appartient pas à l’organisation.',
  ORGANIZATION_ESTABLISHMENT_EXISTS: 'Cet établissement fait déjà partie de l’organisation.',
  ORGANIZATION_LIMIT_REACHED:
    'Vous avez déjà une organisation. Chaque commerçant ne peut en avoir qu’une.',
  ORGANIZATION_NOT_YOURS: 'Vous ne pouvez consulter que votre propre organisation.',
  PAYOUT_ALREADY_RUNNING:
    'Un versement est déjà en cours. Attendez qu’il se termine avant d’en lancer un autre.',
  ORDER_NOT_AWAITING_PAYMENT: 'Cette commande n’attend pas de paiement.',
  PAYMENT_NOT_FOUND: 'Nous n’avons pas trouvé ce paiement.',
  PAYMENT_ALREADY_SUCCEEDED:
    'Votre paiement précédent a bien abouti. Votre commande a été mise à jour.',
  PAYMENT_VERIFY_FAILED: 'Impossible de vérifier le statut du paiement. Veuillez réessayer.',
  MERCHANT_NOT_FOUND: 'Nous n’avons pas trouvé ce commerçant.',
  PAYMENT_AMOUNT_INVALID: 'Le montant du paiement n’est pas valide.',
  PAYMENT_FAILED: 'Le paiement n’a pas pu démarrer. Veuillez réessayer.',
  PAYMENT_UNAVAILABLE: 'Le paiement en ligne est temporairement indisponible. Réessayez plus tard.',
  SUBSCRIPTION_NOT_YOURS: 'Vous ne pouvez gérer que l’abonnement de votre établissement.',
  SUBSCRIPTION_RENEW_TOO_EARLY:
    'Votre abonnement est actif encore {days} jours. Vous pourrez le renouveler quand il en restera moins de 7.',
  COMMUNITY_FUND_NO_ESTABLISHMENT:
    'Nous n’avons pas trouvé l’établissement lié à votre compte : il n’y a pas encore de fonds communautaire à afficher.',
  REVIEW_NOT_YOURS: 'Vous ne pouvez modifier que vos propres avis.',
  REVIEW_RESPONSE_NOT_ALLOWED: 'Vous ne pouvez répondre qu’aux avis de votre établissement.',
  REVIEW_ORDER_NOT_COMPLETED: 'Vous pourrez donner votre avis une fois la commande récupérée.',
  REVIEW_ORDER_NOT_YOURS: 'Vous ne pouvez évaluer que vos propres commandes.',
  REVIEW_TOO_OLD: 'Les avis ne peuvent être modifiés que pendant 30 jours.',
  REVIEW_ESTABLISHMENT_INACTIVE:
    'Cet établissement n’est pas actif et ne peut donc pas être évalué.',
  REVIEW_OWN_ESTABLISHMENT: 'Vous ne pouvez pas évaluer votre propre établissement.',
  REVIEW_FAILED: 'Impossible d’enregistrer l’avis. Veuillez réessayer.',
  REVIEWS_LOAD_FAILED: 'Impossible de charger les avis. Veuillez réessayer.',
  REVIEW_OFFER_MISMATCH: 'Cette offre n’appartient pas à l’établissement évalué.',
  REVIEW_NOT_FOUND: 'Nous n’avons pas trouvé cet avis.',
  REVIEWER_INACTIVE: 'Ce compte ne peut pas publier d’avis.',
  REVIEW_ALREADY_REPORTED: 'Vous avez déjà signalé cet avis.',
  REVIEW_ALREADY_RESPONDED: 'Vous avez déjà répondu à cet avis.',
  REVIEW_ALREADY_EXISTS: 'Vous avez déjà évalué cette commande.',
  PASSWORD_OAUTH_ACCOUNT:
    'Ce compte se connecte avec Google : il n’a pas de mot de passe à définir.',
  CURRENT_PASSWORD_INCORRECT: 'Votre mot de passe actuel est incorrect.',
  FIRST_NAME_REQUIRED: 'Saisissez votre prénom.',
  LAST_NAME_REQUIRED: 'Saisissez votre nom.',
  PASSWORD_REQUIRED: 'Saisissez votre mot de passe.',
  VERIFICATION_SEND_FAILED: 'Impossible d’envoyer le code de vérification. Veuillez réessayer.',
  INVALID_SETTING: 'Ce paramètre n’est pas valide.',
  MAX_DISTANCE_RANGE: 'Choisissez une distance entre 100 m et 50 km.',
  VERIFICATION_ATTEMPTS_EXCEEDED: 'Trop de tentatives. Demandez un nouveau code.',
  MIN_DISCOUNT_RANGE: 'Choisissez une réduction minimale entre 0% et 100%.',
  CONSENT_NOT_FOUND: 'Aucun consentement actif de ce type.',
  VERIFICATION_CODE_MISSING: 'Demandez d’abord un code de vérification.',
  PHONE_MISMATCH: 'Ce numéro ne correspond pas à celui en cours de vérification.',
  PHONE_VERIFICATION_UNAVAILABLE:
    'La vérification du téléphone est temporairement indisponible. Réessayez plus tard.',
  ACCOUNT_CREATE_FAILED: 'Impossible de créer votre compte. Veuillez réessayer.',
  USER_NOT_DELETED: 'Ce compte n’est pas supprimé.',
  VERIFICATION_CODE_EXPIRED: 'Ce code a expiré. Demandez-en un nouveau.',
  BALLOT_NOT_OPEN: 'Le vote n’est pas ouvert pour le moment.',
  BALLOT_CLOSED: 'Le vote est terminé.',
  NOT_ELIGIBLE: 'Vous n’êtes pas éligible au vote de cette édition.',
  ALREADY_VOTED: 'Vous avez déjà voté pour cette édition.',
  INVALID_PRIZE: 'Ce prix ne fait pas partie du vote.',
  SNAPSHOT_NOT_READY: 'Le vote est en préparation. Réessayez dans quelques minutes.',
  NO_ACTIVE_CYCLE: 'Il n’y a pas de vote communautaire en ce moment.',
  FIELD_LOCKED_AFTER_ACTIVATION: 'Ce champ ne peut plus être modifié : le vote a commencé.',
  VOTE_FIRST_TO_SEE_RESULTS: 'Votez d’abord pour voir les résultats.',
  VOTING_CYCLE_EXISTS: 'Un autre vote est déjà en cours.',
  VOTING_CYCLE_CHANGED: 'Ce vote a changé pendant votre modification. Actualisez et réessayez.',
  VOTING_CYCLE_INVALID_STATE:
    'Cette action n’est pas disponible tant que le vote est à l’état {status}.',
  VOTING_CLAIM_FINAL: 'Cette demande de prix est clôturée et ne peut plus être modifiée.',
  VOTING_CYCLE_NOT_DRAFT: 'Seul un vote en brouillon peut être modifié ainsi.',
  VOTING_NO_COMPLETED_CYCLE: 'Aucun vote terminé n’a encore de prix à réclamer.',
  VOTING_PRIZE_TOP_ONLY: 'Seuls les {count} premiers du classement peuvent réclamer ce prix.',
  VOTING_CLAIM_NOT_FOUND: 'Nous n’avons pas trouvé cette demande de prix.',
  VOTING_SNAPSHOT_RETRY_INVALID:
    'La liste des votants ne peut être reconstruite que pendant un vote ouvert et pas encore prêt.',
  VOTING_CYCLE_NOT_FOUND: 'Nous n’avons pas trouvé ce vote.',
  VOTING_PRIZE_ALREADY_CLAIMED: 'Vous avez déjà réclamé votre prix pour ce vote.',
  VALIDATION_FAILED: 'Certaines informations ne sont pas valides. Vérifiez-les et réessayez.',
  VALIDATION_REQUIRED: 'Ce champ est obligatoire.',
  VALIDATION_EMAIL: 'Saisissez une adresse e-mail valide.',
  VALIDATION_MIN_LENGTH: 'Saisissez au moins {min} caractères.',
  VALIDATION_MAX_LENGTH: 'Saisissez au maximum {max} caractères.',
  VALIDATION_LENGTH: 'Saisissez entre {min} et {max} caractères.',
  VALIDATION_MIN: 'Saisissez une valeur d’au moins {min}.',
  VALIDATION_MAX: 'Saisissez une valeur d’au plus {max}.',
  VALIDATION_NUMBER: 'Saisissez un nombre.',
  VALIDATION_INTEGER: 'Saisissez un nombre entier.',
  VALIDATION_POSITIVE: 'Saisissez un nombre supérieur à zéro.',
  VALIDATION_BOOLEAN: 'Choisissez oui ou non.',
  VALIDATION_DATE: 'Saisissez une date valide.',
  VALIDATION_ENUM: 'Choisissez une des options proposées.',
  VALIDATION_FORMAT: 'Ce n’est pas au format attendu.',
  VALIDATION_PHONE: 'Saisissez un numéro valide, par exemple +21612345678.',
  VALIDATION_URL: 'Saisissez un lien valide.',
  VALIDATION_ID: 'Cet identifiant n’est pas valide.',
  VALIDATION_TEXT: 'Saisissez du texte.',
  VALIDATION_LIST: 'Ce champ doit être une liste.',
  VALIDATION_LIST_MIN: 'Ajoutez au moins {min} éléments.',
  VALIDATION_LIST_MAX: 'Ajoutez au maximum {max} éléments.',
  VALIDATION_COORDINATE: 'Cette position n’est pas valide.',
  VALIDATION_NOT_ALLOWED: 'Ce champ n’est pas autorisé.',
  VALIDATION_INVALID: 'Cette valeur n’est pas valide.',
  ACCOUNT_LOCKED:
    'Trop de tentatives échouées. Votre compte est bloqué pour le moment ; réessayez plus tard.',
  INVALID_CREDENTIALS: 'L’adresse e-mail ou le mot de passe est incorrect.',
  LOGIN_TEMPORARILY_BLOCKED: 'Trop de tentatives de connexion. Patientez puis réessayez plus tard.',
  ACCOUNT_SUSPENDED: 'Ce compte est suspendu. Contactez le support pour obtenir de l’aide.',
  PASSWORD_REUSED: 'Choisissez un mot de passe différent de vos {count} derniers.',
  EMAIL_VERIFICATION_FAILED: 'Impossible de vérifier votre adresse e-mail. Veuillez réessayer.',
  VERIFICATION_RESEND_FAILED: 'Impossible d’envoyer l’e-mail de vérification. Veuillez réessayer.',
  QUERY_TOO_COMPLEX: 'Cette recherche est trop complexe. Simplifiez les filtres et réessayez.',
  TRIAL_EXPIRED: 'Votre abonnement a expiré. Renouvelez-le pour continuer.',
  OFFER_SLOT_CAPACITY_EXCEEDED:
    'Vos créneaux autorisent {capacity} commandes mais seulement {quantity} paniers sont disponibles. Réduisez les commandes par créneau ou ajoutez des paniers.',
  OFFER_CANNOT_REACTIVATE:
    'Seules les offres expirées, annulées ou épuisées peuvent être réactivées.',
  OFFER_CANNOT_TOGGLE:
    'Seules les offres actives ou en brouillon peuvent être activées ou désactivées.',
  ESTABLISHMENT_PENDING_APPROVAL:
    'Votre établissement est en attente d’approbation. Vous pourrez publier des offres une fois qu’il aura été approuvé.',
  ESTABLISHMENT_SUSPENDED:
    'Votre établissement est suspendu : les offres ne peuvent pas être publiées. Contactez le support.',
  ESTABLISHMENT_REJECTED:
    'Votre établissement n’a pas été approuvé : les offres ne peuvent pas être publiées. Contactez le support pour en savoir plus.',
  ESTABLISHMENT_INACTIVE:
    'Votre établissement est inactif. Réactivez-le avant de publier des offres.',
  PHONE_VERIFICATION_REQUIRED: 'Ajoutez votre numéro de téléphone pour passer commande.',
  INSUFFICIENT_STOCK: 'Certains articles de votre commande ne sont plus disponibles.',
  PICKUP_LOCKED: 'Le retrait est bloqué après trop de codes erronés. Contactez le support.',
  ORDER_NOT_READY: 'Cette commande n’est pas encore prête. Attendez la confirmation du commerçant.',
  CODE_EXPIRED: 'Ce code de retrait a expiré : la période de retrait est terminée.',
  PICKUP_ALREADY_DONE: 'Ce retrait a déjà été confirmé.',
  CANCELLATION_WINDOW_CLOSED:
    'Les commandes ne peuvent pas être annulées dans l’heure précédant le retrait.',
  PAYMENT_METHOD_UNSUPPORTED:
    'Ce moyen de paiement n’est pas disponible. Payez en espèces ou en ligne.',
  ESTABLISHMENT_CREATE_FAILED: 'Impossible de créer l’établissement. Veuillez réessayer.',
  USER_LOAD_FAILED: 'Impossible de charger ce compte. Veuillez réessayer.',
  PROFILE_UPDATE_FAILED: 'Impossible de mettre à jour le profil. Veuillez réessayer.',
  LOCATION_UPDATE_FAILED: 'Impossible de mettre à jour la position. Veuillez réessayer.',
  USER_STATUS_UPDATE_FAILED: 'Impossible de modifier le statut du compte. Veuillez réessayer.',
  PHONE_VERIFICATION_FAILED: 'Impossible de vérifier votre numéro. Veuillez réessayer.',
  LOCATION_PREFERENCES_FAILED:
    'Impossible de charger ou d’enregistrer vos paramètres de localisation. Veuillez réessayer.',
  PRIVACY_REQUEST_FAILED:
    'Impossible d’enregistrer votre choix de confidentialité. Veuillez réessayer.',
  PRIVACY_EXPORT_FAILED: 'Impossible d’exporter vos données. Veuillez réessayer.',
  PRIVACY_DELETION_FAILED: 'Impossible de traiter la demande de suppression. Veuillez réessayer.',
  CHALLENGE_PRIZE_ALREADY_CLAIMED: 'Vous avez déjà réclamé votre prix pour ce défi.',
};
