/**
 * Icon font subset guard.
 *
 * The shipped android/app/src/main/assets/fonts/Ionicons.ttf is a SUBSET of
 * the upstream font, generated by scripts/subset-icon-font.js from the icon
 * names actually referenced in src/ (scripts/lib/iconScan.js - shared by the
 * generator and this test, so they cannot drift).
 *
 * WHAT THIS GUARDS
 * ----------------
 * A missing glyph does not throw, log, or fail a snapshot - it renders as a
 * blank box, silently, in production. Nothing else in the pipeline can see it:
 * type-check knows the name union, but the union comes from the full glyphmap,
 * not from the shipped font. So this test parses the shipped file's cmap and
 * asserts every referenced name resolves to a real glyph.
 *
 * If it fails: run `pnpm --filter @foodwaste/mobile assets:subset-icons` and
 * commit the regenerated font alongside the code that added the icon.
 *
 * Mutation-checked at introduction: a subset generated without 'home' made
 * this fail; the full regeneration made it pass.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

// eslint-disable-next-line @typescript-eslint/no-require-imports
const { scanUsedIconNames, loadGlyphMap } = require('../../scripts/lib/iconScan.js') as {
  scanUsedIconNames: () => string[];
  loadGlyphMap: () => Record<string, number>;
};

const SHIPPED_FONT = join(__dirname, '../../android/app/src/main/assets/fonts/Ionicons.ttf');

/**
 * Minimal TTF cmap reader - just enough to answer "which codepoints does this
 * font map to a glyph". Supports subtable formats 4 (BMP segments) and 12
 * (sequential groups), which covers everything an Ionicons subset can be.
 * Self-contained on purpose: a font-parsing dependency would be a heavier
 * contract than the ~60 lines it replaces.
 */
function readMappedCodepoints(fontPath: string): Set<number> {
  const buf = readFileSync(fontPath);
  const numTables = buf.readUInt16BE(4);
  let cmapOffset = -1;
  for (let i = 0; i < numTables; i++) {
    const rec = 12 + i * 16;
    if (buf.toString('ascii', rec, rec + 4) === 'cmap') {
      cmapOffset = buf.readUInt32BE(rec + 8);
      break;
    }
  }
  if (cmapOffset < 0) throw new Error('No cmap table in font');

  const mapped = new Set<number>();
  const subtableCount = buf.readUInt16BE(cmapOffset + 2);
  for (let i = 0; i < subtableCount; i++) {
    const enc = cmapOffset + 4 + i * 8;
    const subOffset = cmapOffset + buf.readUInt32BE(enc + 4);
    const format = buf.readUInt16BE(subOffset);

    if (format === 4) {
      const segCountX2 = buf.readUInt16BE(subOffset + 6);
      const segCount = segCountX2 / 2;
      const endCodes = subOffset + 14;
      const startCodes = endCodes + segCountX2 + 2;
      const idDeltas = startCodes + segCountX2;
      const idRangeOffsets = idDeltas + segCountX2;
      for (let seg = 0; seg < segCount; seg++) {
        const end = buf.readUInt16BE(endCodes + seg * 2);
        const start = buf.readUInt16BE(startCodes + seg * 2);
        if (start === 0xffff) continue; // terminal segment
        for (let cp = start; cp <= end; cp++) {
          const rangeOffset = buf.readUInt16BE(idRangeOffsets + seg * 2);
          if (rangeOffset === 0) {
            // glyph = cp + idDelta (mod 65536); nonzero unless delta maps to 0.
            // Bitwise AND is the spec-mandated arithmetic here, not a typo'd &&.
            const delta = buf.readInt16BE(idDeltas + seg * 2);
            // eslint-disable-next-line no-bitwise
            if (((cp + delta) & 0xffff) !== 0) mapped.add(cp);
          } else {
            const glyphAddr = idRangeOffsets + seg * 2 + rangeOffset + (cp - start) * 2;
            if (buf.readUInt16BE(glyphAddr) !== 0) mapped.add(cp);
          }
        }
      }
    } else if (format === 12) {
      const nGroups = buf.readUInt32BE(subOffset + 12);
      for (let g = 0; g < nGroups; g++) {
        const rec = subOffset + 16 + g * 12;
        const start = buf.readUInt32BE(rec);
        const end = buf.readUInt32BE(rec + 4);
        for (let cp = start; cp <= end; cp++) mapped.add(cp);
      }
    }
  }
  return mapped;
}

describe('shipped Ionicons.ttf covers every icon the app can name', () => {
  const usedNames = scanUsedIconNames();
  const glyphMap = loadGlyphMap();
  const mapped = readMappedCodepoints(SHIPPED_FONT);

  it('scans a non-trivial set of icon names, so a broken scan cannot pass vacuously', () => {
    expect(usedNames.length).toBeGreaterThan(50);
  });

  it('maps every referenced icon name to a glyph in the shipped font', () => {
    const missing = usedNames.filter(name => !mapped.has(glyphMap[name]!));
    // Fix: pnpm --filter @foodwaste/mobile assets:subset-icons, commit the font.
    expect(missing).toEqual([]);
  });

  it('is actually a subset - restoring the full font would silently undo the size win', () => {
    // Full upstream font maps 1,357 codepoints; the app uses ~13% of them.
    // Ceiling sits well above today's usage but far below the full font.
    expect(mapped.size).toBeLessThan(600);
    expect(mapped.size).toBeGreaterThanOrEqual(usedNames.length);
  });
});
