export const BALLOT_DURATION_MS = 48 * 60 * 60 * 1000; // 48 hours

export const VOTING_COUNTER_ID = 'votingCycle';

export const CDN_IMAGE_PATTERN =
  /^https:\/\/(res\.cloudinary\.com|storage\.googleapis\.com|cdn\.toofreshtoowaste\.com)\//;

export const VOTING_ERROR_CODES = {
  BALLOT_NOT_OPEN: 'BALLOT_NOT_OPEN',
  BALLOT_CLOSED: 'BALLOT_CLOSED',
  NOT_ELIGIBLE: 'NOT_ELIGIBLE',
  ALREADY_VOTED: 'ALREADY_VOTED',
  INVALID_PRIZE: 'INVALID_PRIZE',
  SNAPSHOT_NOT_READY: 'SNAPSHOT_NOT_READY',
  NO_ACTIVE_CYCLE: 'NO_ACTIVE_CYCLE',
  FIELD_LOCKED_AFTER_ACTIVATION: 'FIELD_LOCKED_AFTER_ACTIVATION',
  VOTE_FIRST_TO_SEE_RESULTS: 'VOTE_FIRST_TO_SEE_RESULTS',
} as const;

export const VOTING_AUDIT_ACTIONS = {
  ACTIVATE: 'ACTIVATE',
  OPEN_BALLOT: 'OPEN_BALLOT',
  CLOSE_BALLOT: 'CLOSE_BALLOT',
  TALLY: 'TALLY',
  MANUAL_TALLY: 'MANUAL_TALLY',
  ARCHIVE: 'ARCHIVE',
  EXPIRE: 'EXPIRE',
  RETRY_SNAPSHOT: 'RETRY_SNAPSHOT',
} as const;
