import { randomIntBetween } from 'https://jslib.k6.io/k6-utils/1.4.0/index.js';

// Tunis area coordinates for location-based tests
const TUNIS_LAT = 36.8065;
const TUNIS_LNG = 10.1815;

export function randomEmail() {
  const ts = Date.now();
  const rand = Math.random().toString(36).substring(2, 8);
  return `k6-test-${ts}-${rand}@test.example.com`;
}

export function randomPhone() {
  const num = randomIntBetween(10000000, 99999999);
  return `+216${num}`;
}

// Random lat/lng within ~10km of Tunis center
export function randomTunisLocation() {
  const latOffset = (Math.random() - 0.5) * 0.18;
  const lngOffset = (Math.random() - 0.5) * 0.18;
  return {
    latitude: TUNIS_LAT + latOffset,
    longitude: TUNIS_LNG + lngOffset,
  };
}

export function newConsumerPayload() {
  return {
    email: randomEmail(),
    password: 'K6TestPass123!',
    firstName: 'K6',
    lastName: 'TestUser',
    phone: randomPhone(),
    role: 'consumer',
  };
}

export function newOfferPayload(establishmentId) {
  const loc = randomTunisLocation();
  const now = new Date();
  const availableUntil = new Date(now.getTime() + 4 * 60 * 60 * 1000);

  return {
    establishmentId,
    title: `K6 Test Offer ${Date.now()}`,
    description: 'Load test offer — auto-generated by k6',
    originalPrice: randomIntBetween(5, 30),
    discountedPrice: randomIntBetween(2, 10),
    quantity: randomIntBetween(1, 10),
    category: 'mixed',
    availableFrom: now.toISOString(),
    availableUntil: availableUntil.toISOString(),
    pickupLocation: {
      type: 'Point',
      coordinates: [loc.longitude, loc.latitude],
    },
  };
}

export function newReviewPayload(establishmentId, orderId) {
  return {
    establishmentId,
    orderId,
    rating: randomIntBetween(3, 5),
    comment: 'K6 load test review — great food rescue experience!',
  };
}
